### ISSUE TITLE
Specification of multiple error of relative nodes

### ISSUE THREAD

**Issue by chengchingwen** [compiler-s20/discussion#101]
Hi @Naetw,

在 #94 當中討論了關於 declaration error 先發生所以不去檢查後續相關 error (不同Node上的group1是共通的)的議題，但具體的 spec 是怎麼樣的？舉例來說：

```pascal
var err: array 5 of integer;

func(a: integer)
begin
    var err: array 3 of array 0 of integer; // declare error

    // 1. 
    print err[1.0];

    // 2.
    print err[1];

    // 3.
    print err[2][4];
end
end
```

這段 code 當中的 1.2.3. 應該要報什麼樣的錯誤？

**Comment by Naetw** [comment]
Hi, @chengchingwen 

都不會報錯。`func` 內的 `err` 宣告已經蓋掉全域的 `err`，所以 1, 2, 3 都是看到 `func` 內的 `err`，又因為它有宣告錯誤，所以都會被 `VariableReference` group1 的第三點給擋下檢查。

> 不同Node上的group1是共通的

啊啊，這個不是那麼精確，昨天沒注意到 group1 以為是在講 group。我覺得同學不用自己去想 group 之間的交互影響（往年就是需要，導致問題很多），基本上會互相影響的我都列在對應的 group 裡了，像是 variable reference 裡面可能會被 variable declaration 影響，這個就會被我列在裡面。

**Comment by chengchingwen** [comment]
Hi @Naetw 
> `func` 內的 `err` 宣告已經蓋掉全域的 `err`

若是這樣的話，那：

```pascal
func(a: integer)
begin
    var err: array 5 of integer;
    var err: array 3 of array 0 of integer; // redeclare error

    // 1. 
    print err[1.0];

    // 2.
    print err[1];

    // 3.
    print err[2][4];
end
end
```

這種情況應該要以哪個 `err` 為主？

> 我覺得同學不用自己去想 group 之間的交互影響，基本上會互相影響的我都列在對應的 group 裡了

老實說我其實看不太懂 0x02. Semantic Definition 的 group 代表什麼，不知道能不能再解釋一下？

**Comment by Naetw** [comment]
> 這種情況應該要以哪個 err 為主？

第一個 `err` 為主，因為第二個遇到重複宣告，所以沒有被放進 symbol table 裡。

> 老實說我其實看不太懂 0x02. Semantic Definition 的 group 代表什麼，不知道能不能再解釋一下？

前面提到說以前只列出各個節點需要檢查的語意錯誤，需要同學自己去想交互影響的情況下要不要繼續檢查的問題，所以在這次修改的構想中，原本想讓不同節點內的各類語意分組，然後再用參照的方式，列出說在檢查 A 節點的 groupX 的時候需要考慮 B 節點的 groupY 之類的，但後來發現這樣其實會蠻亂的，而且其實每個節點的語意其實除了像 BinaryOperator 之外，其他都蠻單調所以也不好分組。
因此最後就變成目前的形式，當初發放作業前發現時間有點趕（看錯行事曆 Orz），就沒有再多想該用什麼樣的格式說明比較好，而把舊有 group 的格式留下，造成困擾不好意思。

group 目前的作用基本上應該只有同學在問問題時，可以直接點出在詢問哪個節點的哪個 group 而已。

**Comment by chengchingwen** [comment]
> 幫助同學在做語意檢查時，同個 group 的錯誤先找到一個，後續就不需要檢查而已。

所以基本上只要按照：

1. 檢查同個 group 的 error 有無發生
2. 若有，跳過該 group error
3. 若無，按照  0x02 該種類內的順序檢查有無錯誤

這樣的步驟做就可以嗎？

**Comment by Naetw** [comment]
不太確定同學的意思，這邊直接舉個例子：

你在用 SemanticAnalyzer 去巡訪 AST 時，假設現在遇到 `FunctionInvocation`，在對應的 `visit(FunctionInvocationNode *)` 裡面做的事情就是 0x02 中 `FunctionInvocation` Group1 所列的那幾件事：

```
visit(FunctionInvocationNode *node) {
    // 1. Check identifier
    // 2. Check kind of symbol
    // 3. Check # of arguments
    // 4. Traverse arguments
}
```

然後每一點都是有誤就 return 跳離該函式。

**Comment by chengchingwen** [comment]
另外再確認一下
```pascal
var err: array 3 of array 0 of integer; // redeclare error
```

這個重複宣告同時也有 0 dimension size，這樣是只報 redeclare error 就好嗎？

**Comment by Naetw** [comment]
> 這個重複宣告同時也有 0 dimension size，這樣是只報 redeclare error 就好嗎？

是的

**Comment by chengchingwen** [comment]
有點頭緒了，謝謝
