### ISSUE TITLE
無法寫入檔案的字元

### ISSUE THREAD

**Issue by idoleat** [compiler-s20/discussion#103]
我發現我如果使用 cstring library 或是 string library 處理從 Ast node 取得的字串，像是 `getNameCString()`, `getNameCString()` 等，就會讓跑測資的 python 腳本無法用 UTF-8 decode，進而無法寫入致檔案。
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 5756: invalid start byte
Makefile:4: recipe for target 'test' failed
```
使用終端機是可以直接顯示出來的，只有寫入測試結果不行。

請問是我哪裡有操作錯誤，或是我還需要多什麼額外處理呢？謝謝。

**Comment by idoleat** [comment]
執行測試我最新的commit就可以重現錯誤

**Comment by Naetw** [comment]
Hi, @idoleat 

問題不是你使用了 cstring library，我也是使用同一個函式庫。問題是你應該把某個不乾淨的字串（內容實際上是某個 address 殘渣）傳給你的 error message queue 裡，而那些 non-printable 字元有些 utf-8 不認得，就發生錯誤了。

@ianre657 會發 `test.py` 的 patch 到你的 repo，它可以輔助你除錯。

**Comment by ianre657** [comment]
我應該發到所有人的 repo 來擾民拉哈哈
同學等我一下下

**Comment by idoleat** [comment]
好的，感謝助教

**Comment by ianre657** [comment]
@idoleat 
更新摟，現在的測試可以幫同學抓到錯誤了
容我貼一下你的情況秀給大家看看遇到類似問題會看到什麼輸出
![test-img](https://user-images.githubusercontent.com/13212935/84921380-f958a100-b0f6-11ea-9e59-5e1b575629ee.png)

感謝你的發問
