### ISSUE TITLE
about AdvSema

### ISSUE THREAD

**Issue by rum2mojito** [compiler-s20/discussion#107]
助教好，請問AdvSema解答裡沒有symbol table是正確的嗎？感覺很怪＠＠
如下圖（沒有symbol table）：
<img width="1136" alt="Screen Shot 2020-06-18 at 12 45 13 PM" src="https://user-images.githubusercontent.com/26761767/84979293-abc54e00-b161-11ea-99bb-73182492a785.png">

--
@compiler-s20/2020-teaching-team

**Comment by Naetw** [comment]
Hi, @rum2mojito 

這個測資是故意不印的，是用來測試同學 pseudocomment D 的開關功能。
