### ISSUE TITLE
VariableReference測資解答是否遺漏line 18 error in declaration?

### ISSUE THREAD

**Issue by vakerlee** [compiler-s20/discussion#108]
@Naetw 

助教請問VariableReference測資解答是否遺漏line 18 error in declaration?
patch3雖然移除[1.0]非integer的錯誤
但不是應該為宣告錯誤？
source code有註解為error in declaration
但底下的error messages卻沒有出現？
請問是否如我理解的相同？
謝謝

**Comment by Naetw** [comment]
Hi, @vakerlee 

在 `VariableReference` 的 Group1 中有條規則是：

- There is no error in the node of the declaration of this symbol. (no error message needed here)

error in declaration 確實有發生，但是它在 line 9 就被回報了，到 line 18 時，它嘗試去做 reference 發現有誤，就直接離開也不用印錯誤訊息（因為在前面就回報過了）。
