### ISSUE TITLE
[新手上路]hw0 Docker執行error

### ISSUE THREAD

**Issue by CCHsu365** [compiler-s20/discussion#11]
Hi 助教
執行到 ./activate_docker.sh 出現error，看了一些資料還是無法解決，還請麻煩協助，謝謝

![image](https://user-images.githubusercontent.com/61822172/76719884-1dae8580-6776-11ea-8690-6c987da37580.png)

系統
virtual 6.1.4
ubuntu 16.04LTS 64bit

------------------------------------
寫些你想要的東西，但為了其他人的閱讀方便，請注意中英文之間最好加個空格。
如果改不了這個習慣的話，就請安裝這個[插件](https://chrome.google.com/webstore/detail/%E7%82%BA%E4%BB%80%E9%BA%BC%E4%BD%A0%E5%80%91%E5%B0%B1%E6%98%AF%E4%B8%8D%E8%83%BD%E5%8A%A0%E5%80%8B%E7%A9%BA%E6%A0%BC%E5%91%A2%EF%BC%9F/paphcfdffjnbcgkokihcdjliihicmbpd?hl=zh-TW)
改不了別人的習慣，就讓自己的世界美觀一點。

**Comment by ianre657** [comment]
@CCHsu365 
同學你好
這堂課程未來希望是一個問題一個 issue，方便其他同學來尋找問題
所以能否請你額外開一個 issue ，我們在那邊討論如何？

**Comment by CCHsu365** [comment]
已新開issue, 謝謝
