### ISSUE TITLE
請問frame pointer 指的位置?

### ISSUE THREAD

**Issue by CCHsu365** [compiler-s20/discussion#110]
定義說的是bottom of current ARI,  是指address上的bottom 還是data 上的bottom ? 

stack 是從high address向下長，假設ARI 128 byte,每個data是4byte 
那frame pointer 是指在第128 byte 的位置， 還是第125 byte的位置呢？

圖片是畫在兩個ARI中間， 還是是第129 byte的位置？

謝謝

**Comment by YSHsieh7777** [comment]
同學好，
我會指在 128 byte 的位置，
不過我想指到哪就是根據同學的實作怎麼做，
只要同學可以透過 Frame pointer 知道這個 ARI 的界線在哪即可

**Comment by CCHsu365** [comment]
了解 ，謝謝助教
