### ISSUE TITLE
請問 AdvCond.p 的答案為什麼會是 -1

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#113]
助教您好, 
     我的問題如下圖, 我看了很久, 判斷式 a > b 應該是要走 false branch 才對啊, 如果走 false branch, 答案應該是 -21. 不會是 -1 啊
     還是我有那裡沒弄清楚??

![image](https://user-images.githubusercontent.com/61784186/86103837-d7e0b780-baef-11ea-9340-647df4c8442d.png)

**Comment by YSHsieh7777** [comment]
@compiler-s20/2020-students 

同學好

不好意思 `AdvCond.p` 這個測資助教答案給錯了，
稍後打 patch 給各位同學
