### ISSUE TITLE
test.py line 160 有誤, 導致 bonus case 無法與 sample solution 比對. 

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#116]
助教您好, 
    請見下圖. thanks. 

![image](https://user-images.githubusercontent.com/61784186/86140175-2c515a80-bb23-11ea-9638-cd886ce20a1c.png)

**Comment by YSHsieh7777** [comment]
@pohunghuang-nctu 

感謝同學的提醒！
稍後打 patch 給同學
