### ISSUE TITLE
bonus case: arraytest2 的答案似乎有問題

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#118]
hi, 助教您好
    請見下圖. 最後一個 print 結果應該是 10, 不過您給的答案是 5. 麻煩請確認一下, 謝謝. 

![image](https://user-images.githubusercontent.com/61784186/86310271-3a50c980-bc50-11ea-9af4-6219a0d9495a.png)

**Comment by YSHsieh7777** [comment]
@pohunghuang-nctu 

是，答案有誤
謝謝同學的 debug，
稍後打 patch 給同學
