### ISSUE TITLE
./activate_docker.py: invalid syntax

### ISSUE THREAD

**Issue by CCHsu365** [compiler-s20/discussion#12]
Hi 助教
執行到 ./activate_docker.sh 出現error，看了一些資料還是無法解決，還請麻煩協助，謝謝

![image](https://user-images.githubusercontent.com/61822172/76733372-a855ab80-679b-11ea-9e39-3587249cca41.png)

系統
virtual box 6.1.4
ubuntu 16.04LTS 64bit

**Comment by ianre657** [comment]
@CCHsu365 

同學你好
從你的輸出判斷，我認為這是因為我在寫腳本的時候使用到了 Python3.6 才推出的 [fstring](https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals) 功能

由於你提供的環境是 `ubuntu 16.04LTS`，所以我猜測你電腦的 Python 版本可能是 3.4
你可以透過這個指令來驗證我的假設 :
```sh
$ python3 --version
```

這是我建議的解決方法 :
1. 改使用 ubuntu18.04 (自帶python3.6)
2. 在你系統中安裝 Python3.6 並優先插入到你使用者的 `$PATH` 變數中
3. 升級系統的 Python3 版本 (較不推薦)

**Comment by singlexx5** [comment]
```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

python3 為 3.5.測試錯誤如上一位同學.
```
Python 3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> f'{dirpath}/.history/docker_bash_history'
  File "<stdin>", line 1
    f'{dirpath}/.history/docker_bash_history'
                                            ^
SyntaxError: invalid syntax
```

https://9oelm.github.io/2019-03-13--Updating-python3-on-an-outdated-ubuntu/
造這個解法..
>> 在你系統中安裝 Python3.6 並優先插入到你使用者的 $PATH 變數中

能夠解決.

**Comment by CCHsu365** [comment]
目前重灌ubuntu18.04 已可使用 👍️
