### ISSUE TITLE
請問老師 6/30 錄影課程的投影片 

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#120]
老師您好, 
   課程中有提到 instruction scheduling 的投影片會再上傳到 github, 不過我這幾天好像沒有看到有新的 commit, 請問是尚未上傳還是我弄錯意思了呢? 謝謝老師. 

Best Regards
        Paul Huang

**Comment by ypyou** [comment]
I totally forgot that right after the lecture. Just uploaded.

**Comment by pohunghuang-nctu** [comment]
謝謝老師, 已下載.
