### ISSUE TITLE
[Docs] Git add - incorrect file target

### ISSUE THREAD

**Issue by CCHsu365** [compiler-s20/discussion#13]
Hi 助教
修改完  student_info.ini ，進入docker後，執行 make, 
README.md 開頭已經更新成我的個人資訊。
![image](https://user-images.githubusercontent.com/61822172/76863024-e33e0900-6899-11ea-91b8-d8f1dea1edb1.png)

但使用git status, makefile 沒有被更新。
![image](https://user-images.githubusercontent.com/61822172/76863248-2d26ef00-689a-11ea-9739-db54e94f360c.png)

再麻煩指導，謝謝

系統
virtual box 6.1.4
ubuntu 18.04

**Comment by ianre657** [comment]
@CCHsu365 

同學你好，這次作業並沒有要更新 Makefile
是我在敘述中誤置
原本的 `git add Makefile README.md`

請用 `git add README.md student_info.ini` 或 `git add -A` 其中一個替代

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by ianre657** [comment]
已打 patch
