### ISSUE TITLE
Docker 安裝版本選擇

### ISSUE THREAD

**Issue by TP-YEN** [compiler-s20/discussion#15]
Hi, 助教@ianre657

我在Ubuntu上安裝docker,

有兩個選項:
1. Install Docker on Ubuntu Using Default Repositories
2. Alternative: Install Docker from Official Repository

https://phoenixnap.com/kb/how-to-install-docker-on-ubuntu-18-04

請問這兩個差異是什麼呢?我要選哪一個呢?

謝謝

**Comment by ianre657** [comment]
@TP-YEN 

兩個都可以，但如果你想要方便的話使用第一種就好 (ubuntu default repositories ) 

如果想區分差別的話，你可以看一下 [Using PPA in Ubuntu Linux](https://itsfoss.com/ppa-guide/) 這篇文章
 
第一種方式是從 ubuntu official PPA ，第二種則是從 Docker (這是一家公司，也是 docker 的主要開發商 ) 的 personal PPA 來拉取套件，兩者最常的差別就是軟體版本更新程度，通常是 docker 有釋出新版本時會直接更新自己的 personal PPA ，一段時間後才會推到 ubuntu offical PPA。

兩者間的抉擇，就看你想不想拿最新版的 docker. 而已，但因為這堂課用到的 docker 功能並不多，
照理說不應因為新舊版而有區別

如果真的要區分出差別的話，頂多我們可以根據 ubuntu offical PPA 的更新比較慢來簡單猜測 offical PPA 的版本會比較穩定。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by ianre657** [comment]
@TP-YEN 
嗨，已經回答的 issue 請先暫時不要關閉，這是為了其他同學方便檢索用
助教會在作業結束一段時間後再把 issue 關閉
