### ISSUE TITLE
Is  .001 a valid floating point number?

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#16]
Hi, TAs
   as subject. I have read the README.md, but it seems this case not been mentioned. thanks. 

Best Regards
           Paul Huang

**Comment by Naetw** [comment]
@pohunghuang-nctu 

No. it's not valid since an integral part of a floating point number is a decimal number, which is a sequence of one or more digits.

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by pohunghuang-nctu** [comment]
Hi, 
   also want to know another case,  5.   <== is this also a float?

**Comment by pohunghuang-nctu** [comment]
"5." should not be float, since there's statement, "and fractional part is a sequence of one or more digits".  Sorry for bothering.

**Comment by Naetw** [comment]
Nope. Fractional part should be a sequence of one or more digits as well.

> While integral part is a decimal number and **fractional part is a sequence of one or more digits** without any redundant 0.
