### ISSUE TITLE
Integer constant definition include "negative integer"? like -30

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#17]
Hi, TAs
   README.md said, _"Integer Constants
A sequence of one or more digits. An integer that begins with 0 and followed by other digits is assumed to be octal; otherwise, it is assumed to be decimal."_
   Since no "-" mentioned above. So, for -30 shall be scanned as 2 lexemes, "-" & "30", am I right?

**Comment by Naetw** [comment]
> Q: So, for -30 shall be scanned as 2 lexemes, "-" & "30", am I right?

Yes.

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by pohunghuang-nctu** [comment]
understood, thanks for answer.
