### ISSUE TITLE
It seems conflict among description for "00"

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#18]
Hi, TAs
   In section of "Integer Contstant", it said, _"An integer that begins with 0 and followed by **other** digits is assumed to be octal"_. This shall implied there's should not be a 0 followed 0. 
   But in section of "float constant", it said "00" is an octal number zero. Per my view, it conflict above statement. and further more, if 00 is an octal number zero, how about 000, or 0000 or 00000?

Best Regards
         Paul Huang

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

> Q: This shall implied there's should not be a 0 followed 0.

Sorry for the inaccuracy. "Followed by **any** digits" is more accurate.

> Q: if 00 is an octal number zero, how about 000, or 0000 or 00000?

All of them are octal number zero.

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by pohunghuang-nctu** [comment]
understood, thanks for answer.
