### ISSUE TITLE
docker 下執行make，無法更新README

### ISSUE THREAD

**Issue by TP-YEN** [compiler-s20/discussion#19]
Hi助教@ianre657

如下，請問是遇到什麼問題?
![image](https://user-images.githubusercontent.com/61980180/77329376-dff2c380-6d58-11ea-97aa-2e5ab9436741.png)

**Comment by SZL741023** [comment]
Hi 助教您好 @ianre657 

我也是遇到一樣的問題耶...
再麻煩指教。
thx 
![image](https://user-images.githubusercontent.com/48779231/77343461-a88e1200-6d6c-11ea-8d72-b96d1fe5f2bc.png)

VMware Workstation Player 15.5
Ubuntu 18.04

**Comment by ianre657** [comment]
@TP-YEN @SZL741023 

看到這個輸出是正常的，你們只需要照著指示繼續做下去就好

`update_info.py` 會更新你們的 `README.md` 檔案，但這支程式不會輸出到標準輸出讓你看見結果。
同學可以在 docker 環境使用 make 後下 `cat README.md  | head -n 15` 檢查一下。
在更新完 `student_info.ini` 之後你們要做的事情是到系統環境下使用 git 提交更動紀錄，這部分就請h參照作業敘述以及 #13 的內容

![Screen Shot 2020-03-24 at 6 14 20 AM](https://user-images.githubusercontent.com/13212935/77370896-e014b280-6d9c-11ea-8a86-223479d9fc8e.png)
![Screen Shot 2020-03-24 at 6 12 02 AM](https://user-images.githubusercontent.com/13212935/77370899-e145df80-6d9c-11ea-8bd9-3ce86f54442c.png)
---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by TP-YEN** [comment]
@ianre657 助教好

三個問題

1. 執行cat README.md | head -n 15 後並沒有看到我修改的資訊
![image](https://user-images.githubusercontent.com/61980180/77372172-0c7dfe00-6da0-11ea-9429-eca7f02192a9.png)

2. git status 只顯示 README有被修改過，student . ini 沒有
![image](https://user-images.githubusercontent.com/61980180/77372322-6d0d3b00-6da0-11ea-9824-d61e587685af.png)

3.如何從docker 環境下回上一層資料夾?
![image](https://user-images.githubusercontent.com/61980180/77372460-c2e1e300-6da0-11ea-8f15-d6a732951174.png)
                                                    to
![image](https://user-images.githubusercontent.com/61980180/77372565-dab96700-6da0-11ea-8a40-657d40f8fa62.png)

以上，請助教幫忙~~謝謝

**Comment by ianre657** [comment]
@SZL741023 
我有注意到你使用 sudo 來進入 docker
這個習慣不太好，請根據作業的安裝順序讓你能夠以正常使用者身份存取 docker

**Comment by ianre657** [comment]
@TP-YEN

1. 執行cat README.md | head -n 15 後並沒有看到我修改的資訊
這件事情很奇怪，我猜你可能有動到東西但卻不知道怎麼辦，因為你給的資訊有點太少，我也不在你旁邊沒辦法幫你 debug ，但我有嘗試過 clone 你的專案來測試，是可以正常執行的，所以我暫時先排除是腳本的問題

你可以嘗試重新 clone 一次你的專案，再做看看
還有請你給我這個指令輸出的答案

```shell
$ docker --version && uname -a 
```

2. 因為你已經修改並更新到 github 上了，這部分沒什麼問題，主要是在 1. 上面

3. 請下 exit 指令
```shell
$ exit
```

**Comment by SZL741023** [comment]
@ianre657 

助教好.
其實我有照著步驟安裝。
可是當我執行到make docker-pull之後的步驟 好像都無法操作，所以才會選擇用這種方式進入docker.
（網路上教的..）
下班回去把異常訊息截圖給助教幫忙看看！
感謝🙏

**Comment by ianre657** [comment]
@SZL741023 

你可以參考[Manege docker as a non root user](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user)

在實際意義也是使用 root  權限來操作 docker 
但操作起來會比直接下 sudo 還要安全一些

**Comment by SZL741023** [comment]
> @SZL741023
> 
> > 其實我有照著步驟安裝。
> 
> 我會找時間檢查安裝步驟有沒有問題
> 但我安裝時沒遇到什麼障礙，所以有些盲點會看不到，可能還需要由你提供些訊息幫助完善文件
> 
> 你可以參考[Manege docker as a non root user](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user)
> 
> 在實際意義也是使用 root 權限來操作 docker
> 但操作起來會比直接下 sudo 還要安全一些

已依照助教給的參考解決需要用sudo下指令的問題。
感謝助教。
不過我跟TP同學也是遇到一樣的問題...
執行完cat README.md | head -n 15 後並沒有看到修改的資訊，如下圖。
![image](https://user-images.githubusercontent.com/48779231/77435821-b780cd00-6e1d-11ea-8863-e12364b67912.png)

執行完
$docker --version && uname -a 如下圖
![image](https://user-images.githubusercontent.com/48779231/77436083-00d11c80-6e1e-11ea-994e-58652470cfdf.png)

再煩請幫忙。
thx

**Comment by TP-YEN** [comment]
@SZL741023
Hi, 我依照助教的建議重新clone一次，就可以了。

@ianre657 助教好
目前OK了!感謝~~

**Comment by SZL741023** [comment]
> @SZL741023
> Hi, 我依照助教的建議重新clone一次，就可以了。
> 
> @ianre657 助教好
> 目前OK了!感謝~~

@TP-YEN 
是git remote之後再git clone自己的功課嗎？
剛剛試過了，還是一樣耶...QAQ
![image](https://user-images.githubusercontent.com/48779231/77450380-1f3f1400-6e2e-11ea-9350-56a30622fcb0.png)

**Comment by SZL741023** [comment]
> @SZL741023
> Hi, 我依照助教的建議重新clone一次，就可以了。
> 
> @ianre657 助教好
> 目前OK了!感謝~~

@TP-YEN 
不好意思，請問要怎麼重新Clone啊...
thx

**Comment by ianre657** [comment]
@SZL741023 
你可能要熟悉一下 git 的基本觀念，未來操作作業時才不會花太多時間在這上面

環境提醒路徑已經存在是因為先前你使用 `git clone` 時已經創建了一個資料夾，所以下相同指令時他會偵測到有已存在的資料夾而失敗

在你的情況中，請先刪除自己原本的資料夾

```
rm -rf hw0-SZL741023
```
再用 `git clone`重新拉一份

**Comment by SZL741023** [comment]
> @SZL741023
> 你可能要熟悉一下 git 的基本觀念，未來操作作業時才不會花太多時間在這上面
> 
> 環境提醒路徑已經存在是因為先前你使用 `git clone` 時已經創建了一個資料夾，所以下相同指令時他會偵測到有已存在的資料夾而失敗
> 
> 在你的情況中，請先刪除自己原本的資料夾
> 
> ```
> rm -rf hw0-SZL741023
> ```
> 
> 再用 `git clone`重新拉一份

@ianre657 
好的好的，我會再去惡補一下XD

目前已有看到自己修改過的資訊，再次感謝指教。
謝謝！！

**Comment by SZL741023** [comment]
@ianre657 
hi 助教
我又有問題了...(到底哪來這麼多問題囧rz...
我執行到最後一步要push到github的時候Fail...
是內容版本不同的問題嗎？
thx
![image](https://user-images.githubusercontent.com/48779231/77552587-b075bf80-6eee-11ea-830c-76b4c2ffbff3.png)

**Comment by Naetw** [comment]
Hi @SZL741023 

遇到問題的時候，這類工具都有蠻詳盡的錯誤訊息的提示，一般解決方法有幾個步驟：第一步就是嘗試理解提示，這時候也許看完提示就知道怎麼解決了，像是編譯器告訴你你某個變數沒宣告；若看不懂的話，可以進行第二步試著把提示原封不動地去問 Google 大師，一般來說都可以找到方法，好一點的也能找到問題來源的解釋。

以你這個問題來說，可能的搜尋關鍵字是：

1. git push fail
2. fail to push same ref

以第一個來說，助教就搜尋到了不錯的繁體中文資源：[【狀況題】怎麼有時候推不上去…](https://gitbook.tw/chapters/github/fail-to-push.html)。

助教並非 24 小時待命回答問題，同學可以試著先自己透過 Google 排除問題，以提升雙方的時間利用 - 同學不用乾等助教回覆，助教也可以省下時間回答部分問題；若最後真的不知道怎麼解決，可以上來發問，並可以提到你做了什麼嘗試但最後還是失敗了的相關資訊，如此一來助教可以縮小問題的可能範圍，避免重複提供你已經試過的解法，來提升討論的品質。

**Comment by SZL741023** [comment]
好的好的，有造成困擾真的不好意思。
已順利完成，感謝助教們的幫忙。
thx

**Comment by Naetw** [comment]
@SZL741023 

不會不會，助教主要還是希望同學能夠學到更多，才建議一些方式來提升討論的品質也節省同學的時間。

未來開發上 Git 是很重要的工具，上面提到的資源算是個蠻好入門的介紹，有空的話可以研究一下～
