### ISSUE TITLE
[碩士班] 作業一發布 / 已接受作業學生請打 patch

### ISSUE THREAD

**Issue by ianre657** [compiler-s20/discussion#20]
@compiler-s20/2020-master-students

各位同學好

作業一已經發布
請至以下網頁點選 hw1 連結來接受作業:
[compiler-s20/private/Homeworks](https://github.com/compiler-s20/private/tree/master/Homeworks)

若在此公告之前已經先行接受作業的學生
請到自己的 hw1 repo 下尋找 Pull requests/[Patch] 1-update-submission-info 點擊 merge 來更新你的作業死線資訊

![Screen Shot 2020-03-24 at 9 21 52 AM](https://user-images.githubusercontent.com/13212935/77378483-06dce400-6db1-11ea-9cb1-0f67eb8a536e.png)

---
給各位同學的小提醒
+ 請務必確保在 docker 上可以正確執行測試
+ hw1 要寫報告，報告有算分 (5%)
+ hw1 是最容易拿分的作業，請**把握**機會
+ 接受作業後請確保自己有訂閱自己的作業 repo，未來助教在上面跟同學互動時你才會收到通知

![Screen Shot 2020-03-18 at 4 55 41 PM](https://user-images.githubusercontent.com/13212935/76942893-6cf0e380-6939-11ea-9e31-75df70cfa893.png)

祝大家作業順利 💯

**Comment by pohunghuang-nctu** [comment]
助教您好, 我是專班學生, 因為我hw1 已經 push 上去, 而且這個 change 好像跟我沒甚麼關係, 請問我可以不要 pull 嗎? 謝謝

**Comment by ianre657** [comment]
@pohunghuang-nctu 

基本上我是建議 merge 我們發的 PR，這樣你未來的作業規格才會保持最新版本

> 而且這個 change 好像跟我沒甚麼關係

是的，如果不想的話可以不用 merge，不過這次建議同學練習一下 merge 我們發的 PR 來熟悉未來的更新作業規格書流程

如果你對更新有疑慮的話，可以看一下 `Files changed` 中的更新內容
這樣可以快速知道我們改了什麼

![Screen Shot 2020-03-24 at 11 40 52 AM](https://user-images.githubusercontent.com/13212935/77385865-52e55400-6dc4-11ea-8d7f-d99967768151.png)
