### ISSUE TITLE
請問是否 hw 的 pull request 都一定要 pull?

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#21]
助教您好, 
   今天看到 hw0, hw1 各新增了一個 pull request, 都跟 README.md 相關. 
   這兩個 hw 我都已經完成(commit 內容其實都不影響我的作業)並且已經 push 上去了. 請問我是否一定要 pull 這些 commit? (我記得助教會以 last push 的時間當作作業完成時間)

Best Regards 
            Paul Huang

**Comment by ianre657** [comment]
@pohunghuang-nctu 

在繳交時間判定的話，你的理解是對的
所以我們不會在作業死線前才發更新，真的有的話就會讓評分從寬
但未來我們如果有打 patch 的話對於作業的理解都會以 patch 為準
並且我們會**假設同學知道有這些改動**

未來如果有這種情況的話可以發個 issue 確認一下
（上學期實際打過的 patch 大多都是補充功能居多，幾乎不會出現影響成績的 patch，所以不用太擔心)

我建議同學在繳交期限之前有看到我們發的 PR 都可以盡量 merge 
因為你提到的 push time 只用在遲交判定而已，不會因為特別早交就影響成績

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by pohunghuang-nctu** [comment]
感謝回覆, PR 皆已 merged, thanks.
