### ISSUE TITLE
docker 環境下安裝自定義套件

### ISSUE THREAD

**Issue by singlexx5** [compiler-s20/discussion#23]
Hi TA.
    請問能在 docker image拿到 root 權限嗎?
    
    想要使用vim 當 editor.  直接去 /var/lib/docker 做修改不確定是不是個好方式.
    因此還是先問一下..

**Comment by ianre657** [comment]
@singlexx5 

請你在 docker 環境外編輯你的檔案
課程提供的 container 只用來編譯跟跑測試就好

**Comment by singlexx5** [comment]
@ianre657   是. 謝謝.

**Comment by ianre657** [comment]
@singlexx5 
補充一下

你原本想做的事情用我們提供的進入方法是做不到的
我故意讓課程給出的環境設定成非 root 使用者來避免同學混淆 docker image 的用途

就算真的用 root 權限安裝 vim ，同學如果不製作出新的 docker image (或是保存 container )這些新的改動都會全部消失
