### ISSUE TITLE
Float-point, octal lexical definition and check some requirement

### ISSUE THREAD

**Issue by cypressfong** [compiler-s20/discussion#24]
1. Why the answer of the last test case, "**00123.123**", in "advance_cases/test_cases/9_float.p" is not like the following:
```
<oct_integer: 00> 
<float: 123.123>
7: 00123.123
```
but
```
<oct_integer: 00123>
Error at line 7: bad character "." 
```
This does not meet the floating-point constants rule, shall we? 

2. Shall we need to validate the range of integer/float-point? If out of range, what should we do? Or just print it, no matter what the value of it? Or I do not need to consider this case?

3. The "Test your scanner" part particularly noted the name our own test file. I want to make sure we do not upload our own test file, right?

Thanks.

**Comment by Naetw** [comment]
> 1. Why the answer of the last test case, "00123.123", in "advance_cases/test_cases/9_float.p" is not like the following

According to [Lex.pdf](https://github.com/compiler-s20/private/blob/master/LectureNotes/L4-Lex.pdf) p.32:

> When more than one expression can match the current input, the longest match is preferred.

> 2. Shall we need to validate the range of integer/float-point? If out of range, what should we do? Or just print it, no matter what the value of it? Or I do not need to consider this case?

No, there won't be any test case that contains overflowed integer/float-point.

> 3. The "Test your scanner" part particularly noted the name our own test file. I want to make sure we do not upload our own test file, right?

You don't have to upload your test cases.

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by cypressfong** [comment]
>>1. Why the answer of the last test case, "00123.123", in "advance_cases/test_cases/9_float.p" is not like the following

>According to Lex.pdf p.32:

I know the longest match and rule given first but I think I possibly miss something.
If considering the longest match, "**123.123**" is longer than "**00123**".
But rule given first, the line 2 test case must have error too.
```
<oct_integer: 00>
<float: 9.1>
2: 009.1
```

**Comment by Naetw** [comment]
> If considering the longest match, "123.123" is longer than "00123".

Sorry, I didn't explain it clearly.

Given an input "00123.123", the lex consumes it one by one until no rule can match it, which means "00123" would be the longest match, as an octal number. After that, the lex continues to deal with the rest of the input ".123".

The reason why the case "009.1" is tokenized in that way is that "9" is not part of the octal number. Hence, the longest match would be "00" before moving on to the next character.

**Comment by cypressfong** [comment]
@Naetw , Thanks for your reply.
