### ISSUE TITLE
WSL issue: make docker-pull Error

### ISSUE THREAD

**Issue by vakerlee** [compiler-s20/discussion#25]
我執行到step3: make docker-pull
出現下列訊息：
make: *** No rule to make target "docker-pull". Stop.
請問哪裡出錯了？
謝謝

**Comment by vakerlee** [comment]
![Noname](https://user-images.githubusercontent.com/27858820/77828533-fcc33880-7156-11ea-9e9c-2e3267f157d4.png)

**Comment by Naetw** [comment]
Hi, @vakerlee 

`make` 指令預設是去當前目錄底下找 Makefile 並根據裡面所規定的規則去執行任務。依照你的截圖，你沒有進去你的 repo `hw0-vakerlee`，`make` 在當前目錄就找不到你的 Makefile 並執行 `docker-pull` 這個目標。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by vakerlee** [comment]
Hi @Naetw 

我進去hw0-vakerlee後執行
出現以下錯誤
![Noname](https://user-images.githubusercontent.com/27858820/77840911-d0430700-71be-11ea-9c4c-05a6a3fbdb6f.png)
請問該如何處理?
謝謝

**Comment by Naetw** [comment]
錯誤訊息提到 permission denied，請參考 README 的 [Step 0. 安裝 Docker](https://github.com/compiler-s20/hw0-vakerlee#step0-安裝-docker)，有提到怎麼不用 sudo 來操作 docker；或是把錯誤訊息丟給 Google。

另外前陣子其他同學的發問方式也有相同的問題，請參考：https://github.com/compiler-s20/discussion/issues/19#issuecomment-603936292。

**Comment by vakerlee** [comment]
@Naetw 


多謝助教協助
hw0搞定了
![Noname](https://user-images.githubusercontent.com/27858820/77844670-0bebca00-71db-11ea-8318-38b4e358f3f0.png)

**Comment by KyrieChuang** [comment]
助教好 想問一下
我一樣在第三步驟 make docker-pull 時遇到了問題
我有進到我作業的資料夾裡了 docker安裝也有成功(用version的指令測試過)
但會顯示附圖的錯誤
看了一下discussion跟一些網路的資料都沒能解決
想問一下助教可能的問題在哪裡，感謝助教
![error](https://user-images.githubusercontent.com/44288651/78405921-1c190480-7634-11ea-84b7-5bb3a8ed0d12.JPG)

**Comment by Naetw** [comment]
Hi, @KyrieChuang 

> 看了一下discussion跟一些網路的資料都沒能解決

想問同學有看了哪些網路資料呢？

**Comment by KyrieChuang** [comment]
我有嘗試 `sudo systemctl restart docker` 和 `systemctl start docker.service`
但會顯示
system has not been booted with systemd as init system (pid 1). can't operate. docker ubuntu
還有一些其他方法 但我試了後都沒能解決Cannot connect to the Docker daemon 跟上面這個error
麻煩助教了 感謝

**Comment by ianre657** [comment]
@KyrieChuang 
想請問你的系統是哪個 distribution

又或者是請給我你這個指令的輸出
```
uname -a 
```

如果你是使用 WSL2 的話可以參考看看這篇: https://github.com/MicrosoftDocs/WSL/issues/457

**Comment by KyrieChuang** [comment]
@ianre657 助教我的輸出如下圖
![image](https://user-images.githubusercontent.com/44288651/78421684-21a23900-768c-11ea-913c-d0fccf9bfa10.png)
感謝助教

**Comment by ianre657** [comment]
@KyrieChuang 

看起來你是真的使用 WSL 沒錯，不過我手邊沒有 windows ，這可能會需要你多一點努力

我想看看
```
lsb_release -a
```
的結果

我看到你沒辦法使用 systemd ，所以我會假設你的系統是 Ubuntu 但是是 16.04 之前的版本
這就讓我跟 @Naetw  有點困擾了，我們兩個既有硬體搞到這種東西有點麻煩


如果要最方面的拿到結果的話：我會推薦直接使用
1. 安裝 ubuntu 虛擬機

@Naetw 
如果你想繼續在 WSL 中使用 Docker的話，你必須要先搞清楚自己是使用 WSL還是 WSL2
並用這些關鍵字繼續搜尋下去

不知道 @tigercosmos  有沒有辦法解這個問題

**Comment by KyrieChuang** [comment]
@ianre657 
![image](https://user-images.githubusercontent.com/44288651/78422025-f9680980-768e-11ea-8047-5b838a0d7343.png)
這個是我輸入完的結果
我用的是microsoft store 載下來的ubuntu18.04 不知道跟VM下載的有沒有差

**Comment by tigercosmos** [comment]
I have studied docker for WSL, and I encountered many problems. Mainly because of the permission I thought, that's why in HW0's tutorial said VM is the best choice for Windows.

**Comment by tigercosmos** [comment]
WSL still not a real standalone Linux, so it lacks many features.
