### ISSUE TITLE
keywords 是不是只有小寫?

### ISSUE THREAD

**Issue by bach8517** [compiler-s20/discussion#27]
as title

**Comment by Naetw** [comment]
是。

**Comment by ianre657** [comment]
我認為這不該是個問題

> The following keywords are reserved words of P (Note that the case is significant):
> array, begin, boolean, def, do, else, end, false, for, integer, if, of, print, read, real, string, then, to, true, return, var, while

這邊已經寫得很清楚了
未來如果發現這種單純沒看規格的問題 @Naetw 應該直接引導同學看文件就好

但如果同學認為是規格不明確導致請在問題中附上是哪些地方讓同學產生疑惑
不然這樣單純回答過於簡單的問題對作業規格改進有害
