### ISSUE TITLE
HW1 的 example 

### ISSUE THREAD

**Issue by zxasdc** [compiler-s20/discussion#28]
請問hw1 example 如下圖紅匡處 是不是有少？

![未命名](https://user-images.githubusercontent.com/51395496/77847612-11540f00-71f1-11ea-9102-8b68098edd10.png)

**Comment by Naetw** [comment]
> 請問hw1 example 如下圖紅匡處 是不是有少？

若同學指的是某些 source code 跟 token 消失，那應該是忘記 pseudocomment 的作用。另外問問題可以再更精確一點，例如你認為少了什麼可以描述一下，否則助教只能通靈看看了 QQ

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by zxasdc** [comment]
確實是 忘記 pseudocomment 謝謝助教提醒

**Comment by ianre657** [comment]
@zxasdc 

請不要主動關閉 issue 
助教會在作業結束後關閉

**Comment by zxasdc** [comment]
@ianre657 

不好意思 沒注意 謝謝助教提醒
