### ISSUE TITLE
請問有關 basic_case\sample_solutions\11_pseudocomment 的問題

### ISSUE THREAD

**Issue by jick155** [compiler-s20/discussion#29]
as title , 關於scanner.l 裡面的linenum ，就我理解是有幾行就會有幾行linenum出來，basic_case 1-10都這樣沒錯，但case11 只印4 只後的都沒印出

舉例：
        test case : begin

        sample solution say : 
                                          <KWbegin>
                                          1: begin    // 在case 11 這裡第五行後就沒印了。

如果答案沒問題，我在找其他方式處理，謝謝

**Comment by Naetw** [comment]
Hi, @jick155 

可以仔細看一下 spec 中關於 pseudocomment 的描述，它們的用途就是開關某些資訊的輸出。所以答案是沒問題的。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by jick155** [comment]
thanks,👍
