### ISSUE TITLE
hw0 out

### ISSUE THREAD

**Issue by ianre657** [compiler-s20/discussion#3]
@compiler-s20/2020-students 

各位同學安安
hw0已經釋出，請到 [private/homeworks](https://github.com/compiler-s20/private/tree/master/Homeworks)
點選作業邀請連結

**Comment by iblis17** [comment]
請教一下，既然用 docker 了，那麼撰寫作業的語言是不是比較有討論空間了？
e.g. 同學 submit Dockerfile 上來

**Comment by ianre657** [comment]
@iblis17 
你好！
我想會有這個疑問是因為同學還沒看過作業1~5，我可以在這邊先說明一下我們的作業方式

使用docker主要只用於統一作業環境，作業繳交的時間仍是會以同學作業repo 的push time為準

批改作業時我們會從GitHub 上拉下同學的繳交的特定 commit，抽換測資來進行自動化批改

對於使用不同語言跟工具來作業，我個人保持開放態度，只不過以現有開發的工具要再確保同學的繳交時間會需要再構思其他辦法，所以在這裡我傾向不支持繳交docker file

但這並不代表完全沒有自由，我們在往後作業會開放同學使用c/c++ 自行實踐。只要同學可以在我們提供的docker image 下使用make成功建置而且達到正確輸出就可以拿取分數

如果同學有任何想法可以再提出
謝謝

**Comment by ianre657** [comment]
@iblis17 
順道一提，這是我們的課程工具
https://github.com/ianre657/invisible-hand

有興趣的話也可以協助開發

**Comment by seabookliu** [comment]
請問一下如果找到不錯的教學網站也可以在這邊分享嗎？

**Comment by ianre657** [comment]
@seabookliu 

這是課程討論區，分享的內容跟課程真的有關的我認為可以
請直接開 issue 標明分享就好

**Comment by vakerlee** [comment]
請問助教

我要接受hw時出現該畫面
"Authorize github"無法點選
請問發生什麼事了？
謝謝

**Comment by ianre657** [comment]
@vakerlee 

能不能附個圖？我對通靈術只有略懂

**Comment by vakerlee** [comment]
請問如何在此貼圖？
第一次使用GitHub
謝謝

**Comment by ianre657** [comment]
@vakerlee 

可以參考[這裡](https://lmgtfy.com/?q=how+to+attach+a+picture+to+github+issue+)

**Comment by nashi5566** [comment]
是卡在 OAuth 嗎？ 要不要試試看在你用的瀏覽器先登出之後再重新登入一次

**Comment by ianre657** [comment]
@vakerlee 

我有嘗試幫你找看看原因，但我手上沒有你的電腦，所以可能要請你確認看看是不是這種情況

1. [Authorization Failed to enable git button](https://github.com/TcsMsTeams/GitHub-TeamsApp/issues/1)
2. [Unable to authorize app - MS Teams](https://github.com/TcsMsTeams/GitHub-TeamsApp/issues/1)

你可能可以
1. 更新你的瀏覽器
2. 重新登出再登入 (照著 @nashi5566 的說法，但我不確定為什麼) 

如果都沒結果的話還請你提供一下你的瀏覽器 browser 類別跟版本
或提供一些你覺得可能有幫助的資訊給我

**Comment by vakerlee** [comment]
重新登入就可以了
謝謝助教
