### ISSUE TITLE
Execute: ./parser [input file]

### ISSUE THREAD

**Issue by TP-YEN** [compiler-s20/discussion#31]
@ianre657助教您好，

請問我修改完scanner.l後，接下來是要Execute: ./parser [input file]?之後才make test?

[input file]在這邊指的是什麼意思?

**Comment by ianre657** [comment]
Execute 是告訴你該如何使用這次編譯出來的程式，如果你沒有自己寫測資的話不會用到
想嘗試的話... 老師上課應該有提過請自己搞懂他的意思

如果只是要編譯跟測試的話，請參照 Build project 跟 Test your scanner 兩個段落來執行作業

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
