### ISSUE TITLE
About basic_cases/10_comment

### ISSUE THREAD

**Issue by rum2mojito** [compiler-s20/discussion#34]
助教好，

- basic_cases/10_comment.p 的內容如下:
```
/* 
comment 
*/
// comment
```

- sample_solutions/10_comment的解答卻是:
```
1: /* 
2: comment 
3: */
```

似乎miss掉EOF的case了～不知道解答這樣算正確嗎？謝謝～

**Comment by Naetw** [comment]
Hi @rum2mojito 

依照作業給大家的 template 設計，LIST 並印出的行為是在遇到 newline 才會執行的，所以以這樣的設計方式來看解答是正確的，因為 `// comment` 後並沒有 newline。不過這的確是我們在生成測資時沒有處理好的部分，同學不需要特別處理。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by rum2mojito** [comment]
👍
