### ISSUE TITLE
Permission denied: 無法存取 /docker/.history/docker_bash_history

### ISSUE THREAD

**Issue by Benson0306** [compiler-s20/discussion#36]
我在執行./activate_docker.sh 時，遇到如標題error。
加了sudo 之後錯誤訊息變成：
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/benson/hw0-Benson0306/docker/.history/docker_bash_history\\\" to rootfs \\\"/var/lib/docker/overlay2/402932510e2a32ad3fea0e8b96e16c79d7169259bbc2e909c6230c5cb5555101/merged\\\" at \\\"/var/lib/docker/overlay2/402932510e2a32ad3fea0e8b96e16c79d7169259bbc2e909c6230c5cb5555101/merged/home/student/.bash_history\\\" caused \\\"open /var/lib/docker/overlay2/402932510e2a32ad3fea0e8b96e16c79d7169259bbc2e909c6230c5cb5555101/merged/home/student/.bash_history: permission denied\\\"\"": unknown.

試著對docker_bash_history使用chmod 777一樣不行

**Comment by Benson0306** [comment]
solved👍

**Comment by Benson0306** [comment]
solved👍👍

**Comment by ianre657** [comment]
@Benson0306 
請寫一下你是怎麼解決問題的
這樣的內容才會對其他同學有幫助

**Comment by Benson0306** [comment]
將hw0搬到其他自訂資料夾即可（不可直接載到～目錄）。
