### ISSUE TITLE
regular expression for floating point 

### ISSUE THREAD

**Issue by Benson0306** [compiler-s20/discussion#38]
助教好
我不是很了解要如何達到hw1有關浮點數的RE，
根據題目要求，以下是我設的計程式碼
(0|^[1-9][0-9]*)\.(0|[0-9]*[1-9]+)   { tokenFloat(); } 
無法正確scan到123.456
想請問能否助教請益，謝謝

**Comment by YSHsieh7777** [comment]
同學好

同學應該要把你設計的 regular expression 展開來看看能不能 match 到 123.456
是不是漏掉了 `+` 還是 `*` 之類的

**Comment by ianre657** [comment]
@Benson0306 
你可以用一些線上 regex tester 來初步測試你的 regex 是不是符合預期
https://regex101.com/

**Comment by Benson0306** [comment]
(0|[1-9][0-9]*)\.(0|[0-9]*[1-9])  works ~👍

**Comment by ypyou** [comment]
@Benson0306 Do not copy and paste your implementation here.

**Comment by ianre657** [comment]
@Benson0306 

恭喜寫出你要的結果
但課程只鼓勵交流大概念，不希望同學直接拿到詳解
未來如果有看到類似內容會直接刪文

**Comment by Benson0306** [comment]
OK I got it
