### ISSUE TITLE
作業繳交問題

### ISSUE THREAD

**Issue by Benson0306** [compiler-s20/discussion#39]
請問作業需要先把hw0的student_info.ini複製到hw1嗎？ 
另外想問一下要去哪裏執行git push XD 是在DOCKER裡面嗎？謝謝！

Thanks!

**Comment by ianre657** [comment]
同學你好
hw0 只是為了讓同學熟悉作業環境，跟 hw1 並沒有關聯
請你閱讀 Readme 中的 Project Structure 跟 Submitting the Assignment 段落
如果有不懂再提問

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by Benson0306** [comment]
👍
