### ISSUE TITLE
advance case 10_scientific

### ISSUE THREAD

**Issue by TP-YEN** [compiler-s20/discussion#40]
@ianre657 助教好

請問此測資
00123E4 answer is 
<oct_integer: 00123>
<id: E4>
3: 00123E4

009e123 answer is 
<oct_integer: 00>
<scientific: 9e123>
4: 009e123

如果00123是oct_integer，為什麼009不是呢?

**Comment by ianre657** [comment]
@TP-YEN 

八進位中的數字只包含 0-7，不會有9

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
