### ISSUE TITLE
diff.txt 的 error訊息解釋

### ISSUE THREAD

**Issue by KyrieChuang** [compiler-s20/discussion#41]
如題
想請問助教跟同學們
![image](https://user-images.githubusercontent.com/44288651/78785848-64407a00-79da-11ea-8501-f40d01bfdd90.png)
像是第9筆跟第12筆測資的error訊息是甚麼意思，上下兩邊好像一樣 
![image](https://user-images.githubusercontent.com/44288651/78785970-9c47bd00-79da-11ea-8d11-4cd10acae65b.png)
跑出來的result也跟解答是一樣
求解 感謝各位

**Comment by Naetw** [comment]
Hi, @KyrieChuang 

同學可以用 `hexdump -C diff.txt` 看一下是不是有一些 non-printable 的字元

**Comment by KyrieChuang** [comment]
![image](https://user-images.githubusercontent.com/44288651/78789870-4f66e500-79e0-11ea-8370-8cb5d48c0ca5.png)
@Naetw  助教好 
我輸出的結果如上圖，應該是右邊那一欄
看起來應該是沒有non-printable的字元

**Comment by Naetw** [comment]
Hi, @KyrieChuang

同學你的答案看起來是多了一個空白 `0x20`，注意第四行 22 2e 22 "20"，第七行則是 22 2e 22 "0a"。不過測試的腳本是有幫 `diff` 加上 `-Z` 的參數去忽略 trailing space 的，同學若沒去動到 `test.py` 的話，你可能要將你目前版本的程式碼推到 repo 上，助教實際去測試一下才可能知道問題點。

**Comment by KyrieChuang** [comment]
@Naetw 助教好
我有測試過空白的部分，但也是一樣，我剛把result下載下來
發現我的error會出現在第一行，但./scanner顯示在最後一行 <<應該是這個問題
我有在report註記了 感謝助教的回答

**Comment by Naetw** [comment]
Hi, @KyrieChuang 

Output 中 stdout, stderr 的順序是我們應該要處理的，之前搬過來的時候忘記更新，導致這次 `test.py` 沒處理好這部分問題，我們會用處理好的版本去改。造成困擾，抱歉。
