### ISSUE TITLE
[在職專班] 作業二發布 / [民調] hw3 小調查

### ISSUE THREAD

**Issue by ianre657** [compiler-s20/discussion#43]
@compiler-s20/2020-inservice-students 

<img width="400" alt="memes" src="https://user-images.githubusercontent.com/13212935/79478399-f2051080-803d-11ea-867b-fe6238423ced.jpeg">

各位同學好

作業二已經發布
請至以下網頁點選 hw2 連結來接受作業:
[compiler-s20/private/Homeworks](https://github.com/compiler-s20/private/tree/master/Homeworks)

❗️ [注意]：碩班學生請不要接受作業 (也可以接受拉，只不過教授還沒教到而已)

給同學的小提醒
+ 作業二的難度還停留在友善級別，說不定作業三就開始升級了ㄛ
+ 要寫報告，報告有算分( 5%)
+ 提早寫作業，不要高估你自己
+ **這次一樣釋出全部測資ㄛ**
+ 如果不知道怎樣用環境的話請參考 #3
+ 接受作業後請確保自己有訂閱自己的作業 repo，未來助教在上面跟同學互動時你才會收到通知

### 民調

@compiler-s20/2020-students 
在作業三開始，開放同學使用 C 或 C++ 來寫作業，但助教有用 C++ 針對 HW3 寫了一連串的教學，最後也沒有幾位同學嘗試用 C 來寫，所以想問同學有沒有人偏好用 C 來專寫作業的，如果沒有的話我們就只會釋出 C++ 的 starter code （也可以少花一些時間準備挖空格）

民調的方式很簡單，請在這邊文章中選擇你要的 emoji 來投票
 
|||
|:-:|:-:|
|C++|C|
|:tada:|:rocket:|

好，感謝大家看完
祝作業順利 💯

**Comment by ianre657** [comment]
同學小心選 C 會後悔ㄛ
真心

**Comment by ianre657** [comment]
@Naetw  會心痛

**Comment by www1800** [comment]
沒意見都可以的一定要投嗎

**Comment by idoleat** [comment]
:tada: 和 :rocket: 是不是有什麼隱藏含意？

**Comment by ianre657** [comment]
@www1800 
沒意見就.. 投 C++吧

@idoleat 
真假拉，沒有威

**Comment by nashi5566** [comment]
希望可以留一點生存空間給純 C ㄉ人QQ
求求助教了QQ

**Comment by ianre657** [comment]
@nashi5566 @idoleat @chengchingwen 

如果說的明確一點，作業三在我們的規劃下會用到多型(Polymorphism) 或是 Visitor pattern ，在本身就內建物件導向概念語言會比較好達成

不是說 C 做不到，只不過同學如果作業三要參照我們給的架構來實踐就會需要多花一份心力去想一下該怎樣辦到，這代表用 C 來做的話，會多學到很多語言上的知識，像 @Naetw 當初在寫 Ｃ的範例 code 就應該學到不少

相比自己嘗試用 C 實踐這些概念，我認為作業三求用 C++ 會省去這部分的麻煩，難度比較適中

不知道這樣說起來夠不夠幫助同學理解作業三用 C/C++ 之間的差別

**Comment by idoleat** [comment]
了解了，不過我也有投C++

**Comment by chengchingwen** [comment]
@ianre657 感謝解釋，不過如果有 C 版本我還是會選擇用 C 實作

**Comment by nashi5566** [comment]
謝謝解釋，但我應該也還是會用 C 寫

**Comment by CCHsu365** [comment]
我也投 C 一票

**Comment by ianre657** [comment]
@compiler-s20/2020-inservice-students 

同學好
作業二在職專班的繳交期限到 5/3(今天) 23:59 截止
請注意我們批改跟遲交標準是看你最後 master branch 最新一個 commit 的 push time
在繳交期限後如果還想要開發，請自己開其他 branch (比如說`dev`) 
並在上面繼續開發，才不會被紀錄成遲交
感謝
