### ISSUE TITLE
[公告] 期中考試安排

### ISSUE THREAD

**Issue by rum2mojito** [compiler-s20/discussion#44]
如題，請問期中考試安排在什麼時候，以及考試範圍～謝謝！

**Comment by ypyou** [comment]
@compiler-s20/2020-students, @compiler-s20/2020-teaching-team 
Here is the midterm exam Info:

@compiler-s20/2020-master-students 
Exam scope : Chapters 1, 3, and 4
Exam time: 13:20-15:10, April 28 (Tuesday)
Exam place: EC015 (designated seats with social distancing)

@compiler-s20/2020-inservice-students 
Exam scope : Chapters 1, 3, and 4
Exam time: 18:30-20:20, April 29 (Wednesday)
Exam place: EC122 (designated seats with social distancing)
