### ISSUE TITLE
請教有關 operators 的 associativity 問題

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#45]
助教您好, 
   在 README.md 中關於 '-' 這個 operator 有一段描述. 

> _The token "-" can be either the binary substraction operator, or the unary negation operator. Associativity is the left. .....

這句話好像是說 '-' 可以當成減號也可以當成負號, 兩者的 associativity 都是 left. 
就我查到的資料, 負號應該是 right associativity, 跟減號是不一樣的. 這邊說兩者都是 left 是特別設計的嗎?

另外關於 not 這個 operator, 從您提供的 test cases 裡面看, 這應該是一個 single operand 的 operator, right associate. 不過說明好像沒有特別提到這個. 想確認一下我的推測跟您的設計是否一致. 

感謝您. 
Best Regards
       Paul Huang

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

> 負號應該是 right associativity, 跟減號是不一樣的. 這邊說兩者都是 left 是特別設計的嗎?

對，同學的理解是正確的。這不是特別設計，應該是少了描述 "and right respectively"，很抱歉造成疑惑。

> 想確認一下我的推測跟您的設計是否一致.

是的。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

---

@compiler-s20/2020-inservice-students 

Spec 中關於 `-` 的描述，它在作為負號時是 right associative，請同學注意。

**Comment by pohunghuang-nctu** [comment]
got it, thanks. :)
