### ISSUE TITLE
function declaration and function definition 的先後順序

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#46]
助教您好, 
    說明中似乎並沒有提到 function declarations block 是否一定要出現在 function definitions block 之前, 或是 function declaration 跟 function definition 是否可以交錯順序出現, 
    從 test cases 裡面觀察,  應該是 function declaration block 是在 function definition block 之前, 想跟助教您確認一下. 

Best Regards
          Paul Huang

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

Grammar rule 要設計成可以接受交錯順序出現。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by pohunghuang-nctu** [comment]
got it and thanks. :)
