### ISSUE TITLE
有人跟我一樣不知從何開始嗎？

### ISSUE THREAD

**Issue by seabookliu** [compiler-s20/discussion#47]
大家好...今天嘗試寫了六小時，結果只在scanner.l加了Return後就掛在第一個decl.p了

助教希望把問題放在這邊討論
以下是我目前碰到的狀況：

嘗試開始寫了一版測試
在scanner.l回傳了KWvar給parser.y
嘗試跑了第一個decl.p Test Case回報是

 Error found in Line #8: var
 Unmatched token: var

當我把return KWvar移除之後
變成
 Error found in Line #8: var ga
 Unmatched token: ga

卡在這邊四小時了，找不出問題
程式一開始寫就死在這邊
我看了document裡面的文件，還是沒有任何頭緒
有人有建議的文件可以讓小弟我研讀的嗎？

**Comment by pohunghuang-nctu** [comment]
parser.output 可以看一下, 裡面包含 grammar rules and parsing tables, 如果有 conflict 這邊也看的到. 
如果想在執行 parser 的時候看到 trace information, 可以在 parser.y 的 declaration section 裡面加 #DEFINE YYDEBUG, 並且在 main 裡面加上 yydebug = 1; (這是既定的 global variable 無須在 parser.y 裡面宣告 ). 以上兩點給你參考.

**Comment by seabookliu** [comment]
我一直都沒發現parser.output這東西，太感謝你了！！
馬上來試試...

**Comment by pohunghuang-nctu** [comment]
https://github.com/compiler-s20/private/blob/master/Documents/bison.pdf  

這個是 bison 的文件. 以上講的都是從這份文件出來的.

**Comment by ypyou** [comment]
Check out slides 27 and 28 in https://github.com/compiler-s20/private/blob/master/LectureNotes/L8-Yacc.pdf

**Comment by seabookliu** [comment]
OK, Many Thanks!

**Comment by seabookliu** [comment]
感謝同學和老師的hint，總算有一些頭緒和成果了 :)
