### ISSUE TITLE
江湖救急, 有人可以傳給我上課的 google meeting 網址嗎? 今晚 E3 維修了 T_T .....

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#48]
as subject, 感恩. 臨時找不到其他地方有記這個網址, 謝謝.

**Comment by pohunghuang-nctu** [comment]
已經在我的 chrome 瀏覽紀錄找到了,  謝謝大家.

**Comment by ianre657** [comment]
能請 @ypyou 幫忙補 google meet 的連結到 [compiler-s20/private](https://github.com/compiler-s20/private) 的 README中嗎？
我一時間也找不到連結
相信未來如果再發生 E3 失效的情況會對其他同學也有幫助

**Comment by ypyou** [comment]
Done ([65fb390](https://github.com/compiler-s20/private/commit/65fb390f4b420746944d75890b8485b2cb3c9130))
