### ISSUE TITLE
#include "y.tab.h" 失敗

### ISSUE THREAD

**Issue by Benson0306** [compiler-s20/discussion#52]
不知道為何執行make時會說找不到y.tab.h
我檢查了Makefile 也有-d 參數
想知道問題大概是出在哪裡
謝謝！

scanner.l:5:10: fatal error: y.tab.h: No such file or directory
 #include "y.tab.h"
          ^~~~~~~~~
compilation terminated.
Makefile:27: recipe for target 'scanner.o' failed
make[1]: *** [scanner.o] Error 1
make[1]: Leaving directory '/home/student/src'
Makefile:12: recipe for target 'project' failed
make: *** [project] Error 2

**Comment by Naetw** [comment]
Hi, @Benson0306 

不好意思，這是我們這邊 starter code 沒調整好。starter code 中的 `scanner.l` 裡面引入了 `"parser.h"`，這應該要對應到在 Makefile 中的：

```
$(PARSER).c: %.c: %.y
        $(YACC) -o $@ --defines=parser.h -v $<
```

但我們在提供 Makefile 時沒有設定好。

yacc (bison) 預設是產生 `y.tab.h`，所以同學有以下做法可選擇：

1. 把 `scanner.l` 中的 `parser.h` 改成 `y.tab.h`
2. 修改 Makefile 讓它產生 `parser.h`

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by Benson0306** [comment]
助教好：
我嘗試了以上做法，錯誤訊息還是存在：（
1. 把 scanner.l 中的 parser.h 改成 y.tab.h
----->錯誤訊息還是在
2.更改Makefile:
$(PARSER).c: %.c: %.y
        $(YACC) -o $@ --defines=parser.h -v $<
------->parser.h有產生了，但錯誤訊息還是在

**Comment by Naetw** [comment]
Hi, @Benson0306 

上面兩種方法是「擇一」嘗試的喔，同學的意思是兩種嘗試都失敗嗎？還是一次嘗試兩種？若是挑哪種都失敗的話，可能要請你把你的 code 推上 repo，助教 clone 下來幫你看看。

**Comment by Benson0306** [comment]
對我是擇一嘗試，
兩種測試法都失敗
好，那我先push上去
麻煩助教了！

**Comment by Benson0306** [comment]
@Naetw  助教好，已經push上去，謝謝助教！

**Comment by Naetw** [comment]
Hi, @Benson0306 

> yacc (bison) 預設是產生 y.tab.h，所以同學有以下做法可選擇：
> 1. 把 scanner.l 中的 parser.h 改成 y.tab.h
> 2. 修改 Makefile 讓它產生 parser.h

這邊的 1 指的是「修改」不是新增，我看你的 scanner.l 裡面有 `parser.h` 又有 `y.tab.h`，一定會有一個沒有，也就會編譯失敗。

目前看起來你的 Makefile 有讓 yacc (bison) 改成吐出 `parser.h`，所以請你把 `scanner.l` 裡面的 `y.tab.h` 刪掉。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by Benson0306** [comment]
謝謝助教的回答，但是我若不加y.tab.h
就會出現類似像：
scanner.l:45:22: error: 'MOD' undeclared (first use in this function)
 ":="  { TOKEN(:=); return ASSIGN;}
之類的錯誤訊息，不知道是不是我少加了什麼
我研究投影片，lexer要work好像跟y.tab.h跟要加retrun {SYBOLNAME}有關係而已？

**Comment by Naetw** [comment]
這個就是你這次作業要做的，你需要在 `parser.y` 定義需要的 token，然後引入 (include) `parser.h` 或是 `y.tab.h` 就是要引入 token 的定義。

既然你已經在 Makefile 讓 yacc (bison) 吐出 `parser.h` 了，那 token 相關的定義就會放在裡面（若沒改，預設就是放在 `y.tab.h`），所以這邊就只能請你自己去 `parser.y` 把需要用到的 tokens 定義好。

**Comment by Benson0306** [comment]
助教抱歉，原來是我犯傻有一些token少定義到！
我原來的意思是我已經將token都設定好了，
不知道為何還會發生錯誤訊息，
已經解決了謝謝助教！
👍
