### ISSUE TITLE
makefile warning

### ISSUE THREAD

**Issue by zxasdc** [compiler-s20/discussion#53]
請問執行make都會有以下warning是否要緊？
![Screen Shot 2020-05-02 at 13 04 47](https://user-images.githubusercontent.com/51395496/80855667-b1300d00-8c75-11ea-9e8a-c29271a2f61d.png)

**Comment by Naetw** [comment]
Hi, @zxasdc 

沒關係，基本上不影響結果。若不想看到可以參考[這篇](https://stackoverflow.com/questions/46213840/get-rid-of-warning-implicit-declaration-of-function-fileno-in-flex)試試。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by zxasdc** [comment]
補充一下 解決warning方式

1. scanner.l 增加
//%option nounput
//%option noinput

2. Makefile CFLAGS 修改
CFLAGS  = -Wall -std=c11 -D_XOPEN_SOURCE=700
