### ISSUE TITLE
一開始var就卡關了

### ISSUE THREAD

**Issue by vakerlee** [compiler-s20/discussion#54]
hi~ 助教
我有加了yydebug
訊息如下：
![Noname](https://user-images.githubusercontent.com/27858820/80861844-b6a44c00-8ca3-11ea-8797-19ce0f724f18.png)
看了parser.output
關於var的grammar顯示為useless
![Noname](https://user-images.githubusercontent.com/27858820/80861886-01be5f00-8ca4-11ea-90ae-9a1891a33153.png)
而我的rules如下:
![Noname](https://user-images.githubusercontent.com/27858820/80861961-392d0b80-8ca4-11ea-9bd6-3cf891b8b8d0.png)
仍然沒有頭緒
我是哪裡搞錯了？
請指引點光明吧...
謝謝

**Comment by Naetw** [comment]
Hi, @vakerlee 

簡單來說，這次作業是要同學透過 grammar rules 來描述一支 P 語言程式的架構。若同學的完整規則就如第三張截圖的話，同學的 parser.y 所產生出來的 parser 所代表的意義是：P 語言的程式架構就只能是「一個 id」或是「一串 id list」。

詳細一點來說就是，若同學沒有透過 `%start` 來指定某一條規則的話，yacc (bison) 預設會是以第一個規則作為開頭；而你第一個規則 (idlist) 沒有使用到任何後續的規則 (datadec, datadef, ...) ，因此後面的規則都會是用不到的。

所以你應該要做的事情是，用 top-down 的方式來撰寫你所有的規則。舉例來說你現在想要寫一個只分析宣告的 parser，那你的規則應該如下（以你截圖所描述的 token）：

```
%%
datadec:
    VAR idlist ":" dectype ";"
;
// rules of idlist, dectype
```

**Comment by vakerlee** [comment]
hi~ @Naetw 

若有多個分析，就必須指定多個%start是嗎？
最後各個分析reducing成各自的start symbol 才會accept是嗎？

> %start datadec1 detadec2
> 
> %%
> datadec1:
>     ID ";"
> ;
> datadec2:
>     VAR idlist ":" dectype ";"
> ;

**Comment by Naetw** [comment]
不是，`%start` 簡單來說指的就是 root rule，所以若你要多個分析就會需要再生一個規則去展開為那兩個規則：

```
%%
Datadec:
    datadec1
    |
    datadec2
;
// rules of datadec1 and datadec2
```

**Comment by vakerlee** [comment]
謝謝 @Naetw 
我瞭解了
