### ISSUE TITLE
測試時會額外加入關於 consecutive operator 的測資

### ISSUE THREAD

**Issue by YSHsieh7777** [compiler-s20/discussion#55]
@compiler-s20/2020-students 

同學好

助教原本釋出的測資中沒有關於 consecutive operator 的測資，
但是看到有同學花了很多時間在這部份上，
因此助教在改作業時會有額外 5 分的 consecutive operator 的測資

**Comment by YSHsieh7777** [comment]
@compiler-s20/2020-students 

補充一下，
之後作業的範例程式碼不會有關於 consecutive operator 的實作，
測資中也都不會有，
同學可以自行選擇是否實做

**Comment by cypressfong** [comment]
如果要算分數的話，可以麻煩助教，釋出這部份的測資嗎？
或許可以不用放到"test/" 底下，直接用回覆的型式也是可以接受的。
謝謝。

**Comment by YSHsieh7777** [comment]
@cypressfong 

同學好
助教會測 spec 提到的 `--a` 和 `not not a`
同學的 parser 要能將第二個 `-` 和 `not` 標示為 unmatched token
