### ISSUE TITLE
搞不懂debug訊息中的state路徑？

### ISSUE THREAD

**Issue by vakerlee** [compiler-s20/discussion#56]
hi~ 助教

查看debug訊息如下：
![debug](https://user-images.githubusercontent.com/27858820/80865690-9aada400-8cbd-11ea-9c2f-d72c1cdb6991.png)
倒數第二行"Entering state 3"
比對parser.output
![state1](https://user-images.githubusercontent.com/27858820/80865744-f11ae280-8cbd-11ea-848f-afcf62717f2d.png)
state 3 不是應該$end to state 8?
然後state 8 accept?
![Noname](https://user-images.githubusercontent.com/27858820/80865808-393a0500-8cbe-11ea-9a34-4b84d5e302ac.png)
為何debug卻直接取下個token VAR?

rules:
![grammar](https://user-images.githubusercontent.com/27858820/80865872-88803580-8cbe-11ea-9099-ec2a5876217f.png)

source code: "decl;" 不是應該被datadec2的rule接受了
但沒有切回stata 0
就直接讀var了？

謝謝

**Comment by Naetw** [comment]
Hi, @vakerlee 

`$end` 指的應該是 EOF (End Of File)，也就是如果讀完 `decl;` 之後 input 檔案內就沒有其他東西了，那它就會 reduce 切到 state 8 然後 accept。

**Comment by vakerlee** [comment]
hi, @Naetw 

可是state3 讀取token VAR就error了
我不了解當"decl;"分析完後為何不會回到state0
如此繼續讀到var才會切換到state2去分析datadec1?

**Comment by Naetw** [comment]
仔細看一下 state 3 有任何規則是吃到 `VAR` 去做 shift 或是 reduce 之類的嗎？沒有的話發生 error 就是正常的，因為它不知道看到 `VAR` 要做什麼。

**Comment by vakerlee** [comment]
hi, @Naetw
 
我一直以為分析要以一行為單位
原來一直都搞錯
感謝助教點出這個問題點
終於有推進了
謝謝

**Comment by Naetw** [comment]
@vakerlee 

Ok, GOGOGO!

P.S. 其實在 https://github.com/compiler-s20/discussion/issues/54#issuecomment-622938916 就有提到要用 top-down 的方式去寫了，看起來還是會有盲點，助教會記得下次可以從 state 的切換來輔助點出這個問題 XD 感謝！
