### ISSUE TITLE
一直卡在decl的測資

### ISSUE THREAD

**Issue by Benson0306** [compiler-s20/discussion#57]
不知道什麼原因一直卡在第一個測資
檢查parser.output也沒有conflicts
以下是我的程式碼”片段“
<img width="678" alt="截圖 2020-05-02 下午11 13 34" src="https://user-images.githubusercontent.com/37235413/80868044-8f14aa00-8cca-11ea-94ce-8875f4c23871.png">

我的variable 的部分有正確的parse
但不知為何就是卡在const
錯誤訊息是
<img width="561" alt="截圖 2020-05-02 下午11 17 50" src="https://user-images.githubusercontent.com/37235413/80868135-28dc5700-8ccb-11ea-9ac2-ac7a0fb72e49.png">

第15行的地方看起來也是有rule可以走
#15 var PI: 3.1415926;

<img width="568" alt="截圖 2020-05-02 下午11 26 04" src="https://user-images.githubusercontent.com/37235413/80868311-4fe75880-8ccc-11ea-8e75-ab803b0ed5c4.png">

scanner.l的部分看起來也是正確的QQ
不知道能否請助教指點一下迷津😭

**Comment by Naetw** [comment]
Hi, @Benson0306 

助教乍看之下看不出問題來（目前沒太多空閒時間），你或許可以透過 `parser.output` 裡面描述的 grammar section 去追蹤一下你的分析進行到 line 15 時，會在哪個 state 應該對發現問題有幫助。

若不想人體追蹤，看了下同學的討論，啟用 debug 模式應該可以幫助你自動追蹤到出問題的 state，啟用的相關方式可以參考 https://github.com/compiler-s20/discussion/issues/47#issuecomment-615691102 或是 Google 看看。

**Comment by Benson0306** [comment]
助教好，我已經按照以下連結加上# define YYDEBUG 1
[https://stackoverflow.com/questions/6948948/bison-error-output](url)
想請問我該去哪裡看trace的過程？因為我看decl檔案裡面沒有？謝謝助教

**Comment by Benson0306** [comment]
👍
