### ISSUE TITLE
declErr何項規則錯誤?

### ISSUE THREAD

**Issue by vakerlee** [compiler-s20/discussion#58]
hi, 助教

請問declErr為何錯誤?
![Noname](https://user-images.githubusercontent.com/27858820/80907503-6af8ad80-8d4a-11ea-86f7-936a96987631.png)
似乎是因為global與local變數的問題
但我看題目說明找不到為何錯誤
能否給點提示?
謝謝

**Comment by Naetw** [comment]
Hi, @vakerlee 

原始碼的註解有提到：

```
/**
 * declErr.p: local variable declaration after statement(s)
 */
```

在 spec 中關於 compound statement 的規則是：

```
begin
 <zero or more variable and constant declaration>
 <zero or more statements>
 end
```

**Comment by vakerlee** [comment]
hi, @Naetw 

看懂了
原來要先宣告
謝謝
