### ISSUE TITLE
HW2  integer type 問題. & parser.output conflict.

### ISSUE THREAD

**Issue by singlexx5** [compiler-s20/discussion#59]
助教你好.

請問 HW2 中的 oct_integer 也會算在 integer type中嗎?

另外 執行 make test 的結果雖是pass的. 但 parser.output 還是有 reduce/reduce, shift/reduce conflict.
請問這些conflict  有需要修正嗎?

**Comment by Naetw** [comment]
Hi, @singlexx5 

> 請問 HW2 中的 oct_integer 也會算在 integer type中嗎?

算，但這個在下一份作業才會需要考慮喔。

> 請問這些conflict 有需要修正嗎?

根據往年的經驗是沒什麼影響，但是同學有空的話可以試著研究 `parser.output` 來重新設計規則把這些 conflicts 全部消除。助教的經驗是這個消除的過程可以讓你的多數規則越寫越精練、漂亮。

**Comment by singlexx5** [comment]
@Naetw  

助教謝謝.  非常感謝.
