### ISSUE TITLE
[新手上路] 順便問一下 HW0

### ISSUE THREAD

**Issue by www1800** [compiler-s20/discussion#6]
不好意思
沒用過 github 練習一下

順便問一下 HW0
好像點著點著就沒步驟了?

謝謝

**Comment by ianre657** [comment]
@www1800 

同學你可以點一下自己新增的作業連結 [hw0-www1800](https://github.com/compiler-s20/hw0-www1800)
未來的作業敘述都會放在同學的 repo 中，而作業0 只要跟著上面做就可以了

**Comment by www1800** [comment]
謝謝助教

請問 docker 是必須的嗎
不曉得為什麼 Ubuntu 安裝完 docker 之後
docker 一直開不起來 (docker: unrecognized service)

試了Google上的一些方法，還是沒辦法的樣子

**Comment by ianre657** [comment]
@www1800 
為了其他同學方便，請你把這個問題開成新 issue
並在上面敘述一下
1. 你是怎麼遇到這個問題
2. 你的環境是怎樣(比如說安裝了什麼東西)
3. 在遇到這個問題時是跑了什麼指令

你的問法太模糊我沒辦法知道發生什麼事情

**Comment by ianre657** [comment]
你可以在自己環境開發
但評分時會以我們提供的 docker 環境作為評分標準

**Comment by www1800** [comment]
謝謝助教
不好意思平日工作忙
太晚回覆
我後來換了台電腦之後可以了（OS 差別在於Ubuntu 18.04->19.10 但我猜應該跟這個沒關係）
