### ISSUE TITLE
Array var/argument specification

### ISSUE THREAD

**Issue by chengchingwen** [compiler-s20/discussion#60]
我沒有在 spec 或 test 找到這下列幾個 case (若是有還請麻煩告知我在哪)
想請問以下這些 array 相關哪些是合法的？
1. var arr: array; 
2. func(a: array); 
3. func(a: array 9 of integer);

**Comment by Naetw** [comment]
Hi, @chengchingwen 

> 1. var arr: array;

spec 中關於 array 宣告的規則是：

```
var identifier_list: array integer_constant to integer_constant of type;
```

所以 array 後面直接接分號是不合法的。

> 2. func(a: array);

在函式宣告的定義那邊提到參數的宣告格式為：

```
identifier_list: type
```

這部分 spec 沒有改好讓它更清楚，不好意思。這邊的 type 指的就是 scalar type 或是 array type，而單單只有 array 就如同第一題是不合法的。

> 3. func(a: array 9 of integer);

合法。

**Comment by chengchingwen** [comment]
Thanks
