### ISSUE TITLE
unused keyword `def`

### ISSUE THREAD

**Issue by chengchingwen** [compiler-s20/discussion#61]
hw1 的 spec 中有一 keyword 為 `def` 但在 hw2 的 test case 以及 spec 中卻完全沒用到，這是不需要了嗎？

**Comment by Naetw** [comment]
Hi, @chengchingwen 

確實沒用到呢 @@ 助教翻了過去的 repo，在 2012 年就沒有用到了，再更以前的記錄也找不到。同學就當沒這個 keyword 吧，造成困擾，不好意思。

**Comment by chengchingwen** [comment]
Thanks for the response.
