### ISSUE TITLE
碩班考卷發放

### ISSUE THREAD

**Issue by YSHsieh7777** [compiler-s20/discussion#63]
@compiler-s20/2020-master-students 

碩班的同學好，
下星期二 5/12 的下午 1:30 - 5:30 我們會把期中考卷和答案放在 EC618 門口，
請同學該時段來拿考卷，
如有問題可敲門進來問，
若有同學不想要成績被其他同學看到的話可以寄信給助教，
助教會先收著考卷，
同學可以敲門進來拿

專班同學的考卷再等等另外一位助教公告

**Comment by idoleat** [comment]
幫忙更正一下，下星期二是5/12

**Comment by YSHsieh7777** [comment]
感謝 @idoleat 

@compiler-s20/2020-master-students 
同學們注意一下是下星期二 **5/12**

**Comment by chengchingwen** [comment]
@YSHsieh7777  我不小心忘記時間了 還能去拿嗎？

**Comment by YSHsieh7777** [comment]
@chengchingwen 

同學如果只是想知道成績的話，
助教可以直接寄信給你，
如果想要拿考卷的話，
可以在下禮拜一 3:30 - 5:00 到 EC618 來拿

**Comment by chengchingwen** [comment]
@YSHsieh7777  那再麻煩助教寄一份成績給我了 <(_ _)>

**Comment by youxanjump** [comment]
@YSHsieh7777 也麻煩助教寄一份給我了，感謝！

**Comment by XiaoLeS** [comment]
@YSHsieh7777 我下週一過去拿, 謝謝！
