### ISSUE TITLE
關於error顯示的問題

### ISSUE THREAD

**Issue by KyrieChuang** [compiler-s20/discussion#65]
助教、同學好
想問一下有沒有人也遇到這個問題
![image](https://user-images.githubusercontent.com/44288651/81202331-0616af00-8ff9-11ea-9877-c864aefab3f5.png)
最後的部分應該要為 no syntax error 

我的error處理的部分是parser裡面原src檔案的function
![image](https://user-images.githubusercontent.com/44288651/81202434-31010300-8ff9-11ea-95ed-8e6ba7ff0505.png)
想了想也覺得應該不是rule的問題，不太明白問題出在哪
真的卡了一陣子了還是上來求救
麻煩各位助教同學幫我解個惑，感謝！

**Comment by Naetw** [comment]
Hi, @KyrieChuang 

你可以把你的 code 推上你的 repo，助教可以幫忙看一下。

**Comment by KyrieChuang** [comment]
Hi ,@Naetw 
已經push上去了，麻煩助教，非常感謝！

**Comment by Naetw** [comment]
Hi, @KyrieChuang 

已在個人 repo 上做回覆。
