### ISSUE TITLE
關於 for statement 定義問題

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#68]
助教您好, 
   以下幾個關於 for statement 的疑問想跟助教請教一下: 
1. HW2 的  for loop 定義似乎比 HW3 的 for loop 定義來的狹窄很多, 
    先看 HW2 的定義: 
    _for identifier := integer_constant to integer_constant do
        <one compound statement>
    end do_
   在看 HW3 的定義:
  _Loop variable declaration
       A declaration node
  Initial statement
      An assignment node
  Condition
     An expression node
  Body
     A compound statement node_

    (1) HW2 的  loop variable 只能 assign 一個 integer value constant, upper bound 也只能是一個 integer value constant. 但 HW3 定義為 assignment, 似乎隱含這個 assignment 的右邊值可能不一定是constant value, 也有可能是 variable reference 或是其他 expression. 
    (2) HW3 定義 for loop 有一個 condition, 屬於一個 Expression. 如果說是 condition 的話, 那這個 expression 應該比較像" idx < 10" 這樣的 relational binary operation, 一邊是 loop variable, 一邊是 boundary value. 不過從 basic_cases/sample_solution/for 裡面看到的例子, 這個 condition 被輸出成一個 constantValue, 當然 constantValue 也是一個 expression, 但意義上, 這個比較像是 boundary value, 而不是 condition. 
    (3) 我的擔心是, 在未來的作業裡面, 是不是可能出現類似 for idx:= (a +b) to (d*e) 這種 case. 就 HW3 的定義來看, 這應該是合法的 for statement. 如果是的話, 在設計上可能就有點不太一樣. 

Best Regards
      Paul Huang

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

用 assignment node, expression node 的確會造成這樣的疑慮，這邊是助教描述上沒有考慮周全的地方。同學請以 hw2 的定義下去實作即可。

感謝同學偵錯。

---

@compiler-s20/2020-students 

同學好，這邊簡單勘誤 spec 上描述不精確的部分：在 `ForNode` 中 assignment 只會是 `loopvar := integer constant`；condition 只會是 integer constant。

**Comment by pohunghuang-nctu** [comment]
感謝助教迅速回覆.
