### ISSUE TITLE
有關Makefile的問題

### ISSUE THREAD

**Issue by XiaoLeS** [compiler-s20/discussion#69]
因為想試著用VP寫寫看，所以make的時候就需要用Makefile-vp這個檔案，而有了下面兩個方式：
方法一：先把Makefile改名，然後把Makefile-vp改成Makefile
（不過要commit的時候就想到，commit時有需要把Makefile改回來嗎？）
方法二：到src裡下`make -f Makefile-vp`

有稍微看了主目錄的Makefile但是沒有看到相關設定，因此想請問助教到時候測試時會是怎麼測呢？不知道我更改檔名或者Makefile會不會有影響呢？

感謝！

**Comment by Naetw** [comment]
Hi, @XiaoLeS 

請使用方法一，並且將變動 commit 上去。

補充：在主目錄的 Makefile 中，關於 target `project` 的指令是：`make -C src/` 因此 make 預設會去 `src/` 底下找 Makefile 進行建構，所以你需要讓你 `src/` 底下的 Makefile 的狀態是能正確編譯你的作業的。（也就是方法一，並 commit）

**Comment by XiaoLeS** [comment]
太好了，謝謝助教！
因為在上課的時候聽助教講解時是說要特別註明自己是用什麼方式實作的，所以我才會想是不是測試時助教會做一些調整，所以Makefile的部分不知道能不能做更動。
如果這樣的話就沒有問題了，謝謝！

**Comment by XiaoLeS** [comment]
太好了，謝謝助教！
因為在上課的時候聽助教講解時是說要特別註明自己是用什麼方式實作的，所以我才會想是不是測試時助教會做一些調整，所以Makefile的部分不知道能不能做更動。
如果這樣的話就沒有問題了，謝謝！

**Comment by ianre657** [comment]
@XiaoLeS 

為了方便其他查找，同學的 issue 助教會在死線過後統一關閉哦
感謝
