### ISSUE TITLE
有關Declarations type的問題

### ISSUE THREAD

**Issue by XiaoLeS** [compiler-s20/discussion#70]
在決定`Declarations`的`%type`的實作時遇到了一些困難，原因是我想使用`vector`這種C++Container，不過在`%union`中不能使用像是下面這種vector的型態。
```
%union {
    std::vector<DeclNode>* list_decl_node;
};
```
不知道用Ｃ＋＋寫的話，除了自己刻linked list之外，有沒有其他方式可以參考呢？

**Comment by Naetw** [comment]
Hi, @XiaoLeS 

你程式碼所用的 pointer to vector 是可以的，只有單純的 vector 是不行的（因為不是 POD type）。細節可參考 Section "C++ Unions"，該段有提到，union 使用上相關的問題。

**Comment by XiaoLeS** [comment]
謝謝助教，我少做了`%code`的部分！

**Comment by Naetw** [comment]
哦哦哦，那我想 spec 可以再補一些使用 container 也要記得用 `%code` 來 include 的敘述。感謝同學提問！
