### ISSUE TITLE
有關Spec中提到之scalar和structured part問題

### ISSUE THREAD

**Issue by XiaoLeS** [compiler-s20/discussion#71]
Spec中有以下建議：
```
Here is a suggestion: Use an enum and a list of integer for the scalar part and the structured part of type respectively.
```
不知道所謂type的scalar part 和 structured part 是指什麼意思呢？
意思是用enum定義不同的type，然後用一個int(?)的array去map到不同type的輸出字串嗎？(這樣感覺用一個char* array比較對？)

**Comment by Naetw** [comment]
Hi, @XiaoLeS 

scalar 跟 structed 分別指的像是 `integer`, `array 10 of integer`（可參見 hw2 spec）。

enum 用來以 readable integer 來表示不同的 scalar type (integer, real, etc.)，list of integer 則用來表示 array 中各個 dimension sizes。
