### ISSUE TITLE
union的資料型別

### ISSUE THREAD

**Issue by Benson0306** [compiler-s20/discussion#74]
想請問union的資料型別有什麼設計的參考方向嗎？
若像是投影片上只有int,double,char*三種的話有什麼缺點呢？

**Comment by Naetw** [comment]
Hi, @Benson0306 

> 想請問union的資料型別有什麼設計的參考方向嗎？

你在不同 rule 間的 yacc action 會需要互動，那這就需要透過 non-terminal (pseudo-variable) 去傳遞不同 rule 間的物件等等，而 non-terminal 能回傳的物件型別取決於 `%union` 的內容。所以參考方向就是你的 non-terminal 需要傳的東西都必須在 `%union` 中有宣告。

> 若像是投影片上只有int,double,char*三種的話有什麼缺點呢？

那你的 non-terminal 就只能傳遞這幾種型別的物件。

**Comment by Benson0306** [comment]
👍
