### ISSUE TITLE
purpose of visitor pattern?

### ISSUE THREAD

**Issue by chengchingwen** [compiler-s20/discussion#75]
不好意思，我看了 tutorial 的說明後還是沒有很理解 visitor pattern 的用途，能不能再說明一下有沒有 visitor pattern 會有什麼差異？

以我目前的理解，使用 vp 主要應該會是在增加 visitor 的情況上面？tutorial 的意思是說單純以 polymorphism 的方式實做會讓 class definition 變太大，所以用 vp 將 visitor 跟 class def 分開，但如果以這種角度下去看，c++ 是支援 dispatch 的，單用 dispatch 似乎也可以達到同樣的效果？

不曉得能不能在這上面多解釋一下？

先謝謝助教。

**Comment by Naetw** [comment]
Hi, @chengchingwen 

想先釐清一下同學這句：

> c++ 是支援 dispatch 的，單用 dispatch 似乎也可以達到同樣的效果？

指的是什麼樣的方式？

就助教的理解，在訪問者範式中也是用到了 dispatch 的概念在裡面：
虛擬函式 `accept` 可以吃進不同的 visitor 去 dispatch 到各個 visitor 中對應不同實際類別的行為函式中。

**Comment by chengchingwen** [comment]
> 指的是什麼樣的方式？

大致的想像是像這樣的東西，不過我不確定會不會動
```cpp
void print_node(ProgamNode *p);
void print_node(VariableNode *p);
```

**Comment by chengchingwen** [comment]
> 就助教的理解，在訪問者範式中也是用到了 dispatch 的概念在裡面

我是不是能理解為這是 C++ 使用 dispatch 的一種方式？

不過這樣的話，實做 VP 的部份的分數，對 C 來說要怎麼判定？

**Comment by Naetw** [comment]
> 大致的想像是像這樣的東西，不過我不確定會不會動

在 visitor 裡面就是這樣設計的。會需要在 node 裡面加上 `accept` 去做多一層的 dispatch 是因為，某些結點會有一串實際上不同節點的列表，像是 binary operator 跟 unary operator 實際上是不同的，但是他們都可以當作 expression，所以如果僅僅只有一層 dispatch 也就是同學上面想像的部分，那遇到下面的情況就會有問題：

```c++
ExpressionNode *node = new BinaryOperatorNode();

visitor.print_node(node); // invoke which one? print_node(ExpressionNode *)?
```

> 我是不是能理解為這是 C++ 使用 dispatch 的一種方式？

助教認為是的，訪問者範式共用到了兩個概念來幫助 dispatch，`self` 指標 + overloading。

> 實做 VP 的部份的分數，對 C 來說要怎麼判定？

虛擬函式的部分實際上就是維護一張 vtable，所以這在 C 裡面可以用函式指標來做到，overloading 的部分可以用手動的方式完成。因此 C 也是做得到 VP 的。

**Comment by chengchingwen** [comment]
> 像是 binary operator 跟 unary operator 實際上是不同的，但是他們都可以當作 expression

等於是透過一層 virtual function 來做 dynamic dispatch 這樣嗎？

> 因此 C 也是做得到 VP 的。

我主要想問的是，既然 C 沒有這些概念，我們實際有不同的作法可以模擬 dispatch，那作業要求是一定有跟 VP 一樣的界面出來，還是只要能做 dispatch 就可以？

**Comment by Naetw** [comment]
> 等於是透過一層 virtual function 來做 dynamic dispatch 這樣嗎？

是的。

> 我主要想問的是，既然 C 沒有這些概念，我們實際有不同的作法可以模擬 dispatch，那作業要求是一定有跟 VP 一樣的界面出來，還是只要能做 dispatch 就可以？

有一樣的介面助教是比較好判斷，但是實際上同學要怎麼做都可以。

**Comment by chengchingwen** [comment]
感謝助教的解答！
