### ISSUE TITLE
yylloc match 問題

### ISSUE THREAD

**Issue by zxasdc** [compiler-s20/discussion#76]
助教好

我在測declaration測資時 會碰到token match正確 action正確 yylloc讀到錯的情況如下圖

![Screen Shot 2020-05-19 at 20 58 32](https://user-images.githubusercontent.com/51395496/82329908-a2d34680-9a14-11ea-87c3-2d2a444f04cb.png)

我嘗試將input pattern 修改為-10 卻可以讀對 但match action是同一個 如下圖
![Screen Shot 2020-05-19 at 21 00 52](https://user-images.githubusercontent.com/51395496/82330165-0c535500-9a15-11ea-8b57-2c93578e894b.png)

目前試了很久想不太透 不知道有沒有什麼我實作上漏掉的

**Comment by Naetw** [comment]
Hi, @zxasdc 

你可能有以下規則：

```
NegOrNot:
    Εpsilon
    |
    NEG
;
```

如此一來，有負號的情況下，你的 location 會是負號的位置；沒負號的情況下，它會拿到 Epsilon 的位置。

**Comment by zxasdc** [comment]
明白 謝謝助教提醒
