### ISSUE TITLE
child node如何連結parent node?

### ISSUE THREAD

**Issue by vakerlee** [compiler-s20/discussion#77]
助教您好，

看完說明開始實作program.cpp
改寫ProgramNode 新增傳入CompoundStatementNode
![Noname](https://user-images.githubusercontent.com/27858820/82351042-a247a980-9a2e-11ea-96a6-8ebf0eab4db3.png)
parser.y改寫如下：
![Noname](https://user-images.githubusercontent.com/27858820/82351184-d753fc00-9a2e-11ea-8e16-0fcf6e5d3305.png)
![Noname](https://user-images.githubusercontent.com/27858820/82351257-f0f54380-9a2e-11ea-8388-c980a1cdcf69.png)
編譯時出現錯誤
$5與SS沒有宣告type
![Noname](https://user-images.githubusercontent.com/27858820/82351449-2f8afe00-9a2f-11ea-8e92-40270af087de.png)
請問我遺漏的什麼步驟?
或是該如何處理?
要在scanner.l給定AstNode?還是定義type?

看到starter code的%union中有AstNode *node;
似乎是跟上述錯誤有關
但沒有頭緒如何處理？

謝謝

**Comment by Naetw** [comment]
Hi, @vakerlee 

> 編譯時出現錯誤
$5與SS沒有宣告type

這個部分在 spec 有舉例喔，在 Section 0x02 的末段，可以找一下。如果看完還是沒有頭緒可以再在底下留言。

**Comment by vakerlee** [comment]
Hi, @Naetw 

範例中的name有明確的token可以於scanner中assign
且有明確的yytext可以assign給identifier
我搞不懂的如果是要在scanner中assign %union中的AstNode* node
但new AstNode卻是在parser中
且yytext可以表示為AstNode?

name先在scanner assign string然後parser終究可以＄1取得
但$$要new AstNode 仍然要先在scanner assign AstNode?
卡在這點想不通
謝謝

**Comment by Naetw** [comment]
Hi, @vakerlee 

同學應該是對 `yylval` 還不夠熟悉，基本上每個 token 都會有自己一個 `yylval`，而 `yylval` 不是只有 scanner 可以寫入而已。

可以看到我們在 scanner 賦予 `yylval` 資料，在 parser 裡面透過 pseudo variable 獲得資料，以 pseudo code 來表示就像是：

```c
// scanner.l
yylval.integer = 10;  // == values[index_of_this_token] = 10;

// parser.y
new SomeNode($1); // == new SomeNode(values[index_of_this_token]);
```

所以其實你在 parser 中，對某個 pseudo variable 做寫入就相當於寫上對應 token 的 `yylval`，並非一定要特地繞去 scanner 去做寫入。

簡單來說，你要透過 non-terminal 在不同規則間傳遞資料，你就透過寫入 `$$` 就好。當然如果你要寫入某個 token 的 pseudo variable，你一定要先對該 token 定義說是什麼型別，否則就會遇到上面 "has no declared type" 的問題。

**Comment by vakerlee** [comment]
Hi, @Naetw 

感謝助教解惑
我應該缺了
%type <CompoundStatementNode*> CompoundStatement
謝謝
