### ISSUE TITLE
return type of ProgramNode?

### ISSUE THREAD

**Issue by chengchingwen** [compiler-s20/discussion#78]
Ast spec 上的 Program Node 有包含一個 return type ，但似乎全部例子都是輸出 void ，這部分有什麼用途嗎？

**Comment by Naetw** [comment]
Hi, @chengchingwen 

真要說用途的話，在下一次作業的語意檢查（檢查 return statement 是否合適）某些實作方法會需要，但非必要就是了，所以同學可以先想看看自己可能會怎麼處理。總之，寫死字串 "void" 放在節點中也是沒問題的。

**Comment by chengchingwen** [comment]
了解了 謝謝
