### ISSUE TITLE
%type directive

### ISSUE THREAD

**Issue by Benson0306** [compiler-s20/discussion#81]
想請問助教若模板寫成：
LiteralConstant:
    NegOrNot INT_LITERAL {
    }
    |
    NegOrNot REAL_LITERAL {
    }
    |
    StringAndBoolean { $$ = $1; }
;
StringAndBoolean:
    STRING_LITERAL { $$ = $1;}
    |
    TRUE { $\<boolean>\$ = $1;}
    |
    FALSE { $\<boolean>\$ = $1;}
;
IntegerAndReal:
    INT_LITERAL { $\<val>\$ = $1;}
    |
    REAL_LITERAL { $\<dval>\$ = $1;}
;
請問IntegerAndReal、 StringAndBoolean、LiteralcConstant的%type該如何定義呢？
小弟不才，查了網路資料都不太了解規則，希望助教能給點方向，
另外不清楚assignment中0X02最後一段的說明，是否就是在說這個問題呢？

**Comment by iblis17** [comment]
> 請問IntegerAndReal、 StringAndBoolean、LiteralcConstant的%type該如何定義呢？

`%type` 就想成是定義 nonterminal/terminal 的 attribute type，
舉例來說 production head 是 nonterminal，這個 production head 的 attribute 表示成 `$$` 。
所以我們用 `%type` 來定義 `$$` 的 type 的，因為很多狀況下會去 assign production head 的 attribute， 像是
```
{
   // c code
   $$ = ...  // 如果不給 type 這裡就不知道 union 怎麼 assign
}
```

> 另外不清楚assignment中0X02最後一段的說明，是否就是在說這個問題呢？


0x02 的最後那段說明，是針對 P language 的 data type 的說明，跟 nonterminal attribute type 無關。
是說你在建立 AST Tree 的過程中，存下 user 寫的 P language code 中的 data type 時，不建議直接用字串保存這個資訊，因為這個 data type 的資訊對 HW4 有用，而用字串存過於簡略，未來程式有可能需要再度大改。

**Comment by Benson0306** [comment]
謝謝助教的回覆，抱歉我沒有解釋清楚
我的問題應該是：像IntegerAndReal有兩種可能的rule,但這兩種rule會assign給他的type都不同，那我要怎麼先定義IntegerAndReal的type?因為他可能是接int或real不是嗎？

**Comment by Naetw** [comment]
Hi, @Benson0306 

> 那我要怎麼先定義IntegerAndReal的type?因為他可能是接int或real不是嗎？

這就是同學需要自己去設計的地方，你可以設計一個資料結構，它可以表示 integer, real, boolean or string 任一種型別，那你的 `IntegerAndReal` 就可以是你設計的這個資料結構。

Hi, @iblis17 

感謝同學幫忙回覆 XD

另外

> 0x02 的最後那段說明，是針對 P language 的 data type 的說明，跟 nonterminal attribute type 無關。

助教在撰寫這段內容時，是認為目前的例子就足以讓同學應用在其他場合；不過目前看起來，若對於整個 yylval 的實作機制不是很熟悉的話，一旦不需要在 scanner 做處理，就還是會不清楚該怎麼去處理其他 non-terminal 的資料傳遞，感謝同學指出，未來應該會加上兩種例子去做說明。

**Comment by iblis17** [comment]
. 謝謝助教的回覆，抱歉我沒有解釋清楚

well, 不過我不是助教

> 我的問題應該是：像IntegerAndReal有兩種可能的rule,但這兩種rule會assign給他的type都不同，那我要怎麼先定義IntegerAndReal的type?因為他可能是接int或real不是嗎？而又像是StringAndBoolean,他可能是接string type或 boolean type的資料，那又要怎麼事先定義他的type(我試過declare兩次不同的型態會有重複宣告的error)

我採取的演算法如下
```c
IntegerAndReal:
    INT_LITERAL { $$ = new ConstantNode(int, $1, ...); }
    |
    REAL_LITERAL { $$ = new ConstantNode(real, $1, ...); }
    ;
```
所以 `IntegerAndReal` 我會用 ConstantNode 這種形態。這樣用 pointer 去處理就能夠用單一 type 了。

**Comment by Benson0306** [comment]
謝謝幾位大神的幫助
小弟好感動😢
我在回去咀嚼一下，謝謝😍
