### ISSUE TITLE
[在職專班] 期中考卷發放

### ISSUE THREAD

**Issue by tigercosmos** [compiler-s20/discussion#83]
@compiler-s20/2020-inservice-students

在職專班的同學好：

本周三 5/27 的晚上 17:00 - 18:30
本周四 5/28 的晚上 17:00 - 22:00
下周三 6/3 的晚上 17:00 - 18:30
可以來 EC618 領取考卷

請同學該時段來拿考卷，考卷會在門口，請自行取回。
如對分數有問題可拍下考卷，寄信給助教反應。

請要來領考卷的同學在下方點讚做統計。
不想領取考卷的同學請寄信給 TA ( compiler-s20@sslab.cs.nctu.edu.tw)，會跟你講你的分數。

p.s.
這次考試
平均 41.71
標準差 19.76

**Comment by tigercosmos** [comment]
本周三 5/27 的晚上 17:00 - 18:30

**Comment by tigercosmos** [comment]
本周四 5/28 的晚上 17:00 - 22:00

**Comment by tigercosmos** [comment]
下周三 6/3 的晚上 17:00 - 18:30

**Comment by vakerlee** [comment]
請問助教～

周3、4晚上都不會去學校
請問可以今天晚上或週4下午2點左右去拿嗎？
謝謝

**Comment by ianre657** [comment]
@vakerlee  
我今天 5:30 會把你的考卷放在 618門口
請你自己來拿摟

**Comment by vakerlee** [comment]
@ianre657 

謝謝助教
