### ISSUE TITLE
"Emit" or "Omit" ?

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#85]
Hi, 助教您好. 
      如下圖,  emit 是發射的意思, omit 是省略的意思, 想確認一下您下圖中的 emit 是要 "發射" 嗎? 還是要 "省略" ? 或是 emit 也有其他的意思, 還請指點一下, 畢竟我個人對英文的理解也蠻有限的. 
![image](https://user-images.githubusercontent.com/61784186/83090707-f821ee80-a0cb-11ea-9e43-91cd3ee47cd6.png)

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

同學的理解是對的 XD 確實是助教搞混用錯了。

---

@compiler-s20/2020-inservice-students 

考量到多數相關內容是一次寫完的，omit 應該全部都被寫成 emit 了，請各位同學注意。等作業說明完成後會再發 patch。
