### ISSUE TITLE
//&D+ or //&D- 在這次作業會用到嗎? 還是在下次會用到?

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#86]
助教您好, 
    在說明裡面看到這次多了一個開關 D, 不過綜觀整個作業的 test cases 好像沒有用到這個開關, 請問會在哪裡用到呢?

Best Regards
         Paul Huang

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

之前是全部測資都開啟的，但有不少同學抱怨說看不到 symbol table 很麻煩，所以這次就全部讓測資預設開啟。我會在隱藏測資 (10 pts) 裡面用到。

**Comment by iblis17** [comment]
請問一下，那麼在 Program Node 之後對 D 做開關是合法的嗎？

如果是合法，那麼 D 跟 S/T 的選項會交錯輸出嗎？那麼誰先誰後有定義嗎？

**Comment by iblis17** [comment]
> In test cases, this option won't be turned on/off in the middle of the program, it will only be set before the ProgramName.

原文這樣寫，但是我關心的是 隱藏測資，請問上面的敘述對隱藏測資適用嗎？

**Comment by Naetw** [comment]
Hi, @iblis17 

> 請問一下，那麼在 Program Node 之後對 D 做開關是合法的嗎？

合法，但對作業輸出結果意義不大。以往因為沒有 AST 的設計，所有行為都寫在 yacc action 裡面，所以當時在中間對 STD 做開關是有效果的；中間關閉的話，它就會有一段沒有 Source, Token, Symbol Table 的輸出。

**Comment by iblis17** [comment]
好的，謝謝
