### ISSUE TITLE
想建議開放 "索取" 隱藏測資

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#87]
助教您好,
    我個人很願意完整的 implement 所有作業開出的 specification, 只是人年紀大了記性不是那麼好, 即便我很認真地看完完整的 readme, 但在 implement 過程中, 我也很難記得所有 spec 的細節. 助教提供的 test cases and sample solution, 其實是很好的開發幫助工具, 一方面確認自己沒有遺漏, 一方面可以確認自己對 spec 的理解是否正確. 
    所以我覺得既然已經花時間寫了 test cases, 為何不讓開發者使用嗎? 還請助教考慮一下, 是否可以開放給有同學索取? 謝謝. 

Best Regards
        Paul Huang

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

Ok，我會考慮看看；若有要開放的話，最晚繳交期限前一週會發 patch。

**Comment by pohunghuang-nctu** [comment]
thanks.

Naetw <notifications@github.com> 於 2020年5月28日 週四 下午12:11寫道：
