### ISSUE TITLE
如果 function redeclared, 還需要push new symbol table and then pop it? 

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#88]
Hi, 助教您好, 
    如主旨, 從 test/basic_cases/sample-solutions/redecl 的內容看起來, 似乎對於 funcSymbolRedecl() 這個重宣告的 function, 還是push 了一個新的 symbol table. 如下圖:
![image](https://user-images.githubusercontent.com/61784186/83331413-d8a3e500-a2c8-11ea-8d6c-05c8151accfe.png)
![image](https://user-images.githubusercontent.com/61784186/83331427-f2452c80-a2c8-11ea-8c08-79315f3b4c76.png)

我想請問的問題是, 即便該 function 的名字已經重宣告(不新增 symbol entry), 但還是要繼續完後面的檢查, 包含 visit child nodes of this function 是嗎?
類似的問題也會發生在 for loop 的 loop variable 重宣告的狀況下, 想一併請教, 謝謝.

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

> 即便該 function 的名字已經重宣告(不新增 symbol entry), 但還是要繼續完後面的檢查, 包含 visit child nodes of this function 是嗎?
> 類似的問題也會發生在 for loop 的 loop variable 重宣告的狀況下

對，設計方式傾向讓編譯器找出越多錯誤越好，所以除了同個 group 內的檢查會互相影響導致不檢查外，不同 group 的問題能檢查就盡量檢查。

**Comment by pohunghuang-nctu** [comment]
了解, 謝謝助教.
