### ISSUE TITLE
loop variable 的 scope 限制. 

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#89]
助教您好, 
    README.md 中有這樣一句話:
_"Unlike the normal variable, the symbol of a loop variable CANNOT be redeclared whether it's in the same scope or the inner scope."_
   1. 因為 For 會產生一個 scope, 這裡面就只有 loop variable 一個 entry, 所以應該不會有其他的 variable 跟他在 "the same scope", 所以您指的 the same scope, 指的是哪一個 symbol table?
   2. 至於 inner scope, 是指 For Node 下面所掛的 CompoundStatementNode 這一層 scope, 還是說包含 CompoundStatementNode 裡面長出來的所有 inner scope? 不管有幾層?

不知道助教方不方便提供更多 loop variable redeclaration 的例子, 或是乾脆寫一個 pseudo code 描述一下 loop variable redeclaration 的檢查邏輯. 我覺得用文字描述起來好像很難講得清楚, 感謝.

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

> 1. 因為 For 會產生一個 scope, 這裡面就只有 loop variable 一個 entry, 所以應該不會有其他的 variable 跟他在 "the same scope", 所以您指的 the same scope, 指的是哪一個 symbol table?

這邊會把 same scope 拉出來提是想指說：loop var 除了與 variable 一樣，在同個 scope 不能被重複宣告外，在 inner scope 也是不能被重複宣告的，是想用來強調的。當然，loop var 就像同學說的，它所在的 symbol table 只會有它一個 entry。或許把它拔掉會比較好，我再想想看。

> 至於 inner scope, 是指 For Node 下面所掛的 CompoundStatementNode 這一層 scope, 還是說包含 CompoundStatementNode 裡面長出來的所有 inner scope? 不管有幾層?

假設一個 symbol table 稱作 A，那麼被 push 在 A 後面的所有 symbol tables 所形成的 scopes 都屬於 inner scope。

> 不知道助教方不方便提供更多 loop variable redeclaration 的例子, 或是乾脆寫一個 pseudo code 描述一下 loop variable redeclaration 的檢查邏輯. 我覺得用文字描述起來好像很難講得清楚, 感謝.

我覺得前面兩個回答完應該就解釋清楚了，若還是有疑問，我再考慮把檢查邏輯直接描述出來。

**Comment by pohunghuang-nctu** [comment]
Inner 的部分我理解了. 下面這個例子應該不算是 inner, 再跟助教確認一下. 

![image](https://user-images.githubusercontent.com/61784186/83333961-e2801500-a2d5-11ea-9656-b014253158a2.png)

**Comment by Naetw** [comment]
> is below loop variable i ok?

Ok. for 會形成新的 scope，而這個新的 scope 相較於 line 3 的 i 是屬於 inner scope，而已經宣告的 i 是一般變數，而一般變數是允許在 inner scope 被同名的變數宣告蓋過去的。
