### ISSUE TITLE
請問兩個關於 BinaryOperator 的問題

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#91]
助教您好, 
    如下圖: 在 test case, "BinaryOperator.p" 中, 
   1. line 77,  vReal mod decimal(), 兩個 operand 分別是 real and integer, 根據 spec, mod 的兩個 operand 都必須是 integer, 且沒有提到 real 會 implicit convert to integer, 為何 sample solution 在這裡沒有報錯?
   2. line 95, "SSLAB" + decimal(); 兩個 operand 分別是 string and integer, 根據 spec, string 連接必須兩個 operands 都是 string, 為何sample solution 在這裡並沒有報錯?

![image](https://user-images.githubusercontent.com/61784186/83419175-40883600-a457-11ea-8eb7-73016cab33de.png)

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

同學的實作是對的，我的實作中 invocation 傳遞資訊的地方漏掉了，導致做判斷時，以為 child 有誤。晚點會發 patch 給同學。

**Comment by pohunghuang-nctu** [comment]
感謝.

Naetw <notifications@github.com> 於 2020年6月1日 週一 下午10:48寫道：
