### ISSUE TITLE
如果 assignment 的 var reference 是 const, expression 是 array, 應該報兩個 error or 一個?

### ISSUE THREAD

**Issue by pohunghuang-nctu** [compiler-s20/discussion#92]
助教您好, 
    如下圖, 在 assignment.p 中, 這個 assignment 看起來有兩個 error, 不過 sample solution 裡面只有一個, 想請問是刻意的嗎? 

![image](https://user-images.githubusercontent.com/61784186/83504804-85fc4000-a4f7-11ea-8243-1ee98ee36eed.png)

**Comment by Naetw** [comment]
Hi, @pohunghuang-nctu 

在同個 group 裡面，只要其中一個檢查發生錯誤，同個 group 的後續檢查都會跳過不做檢查。

上面的例子，variable reference 常數的檢查比較前面，而它也發生錯誤，所以後面的 expression 是不是 array 這個檢查就略過了。

**Comment by pohunghuang-nctu** [comment]
了解了, 感謝.

**Comment by chengchingwen** [comment]
Hi @Naetw ,

同一份測資有一個
```pascal
const := "NO.1" + float; 
```
但報的 error 是
```
<Error> Found in line 24, column 21: invalid operands to binary operator '+' ('string' and 'real')
        const := "NO.1" + float;
                        ^
<Error> Found in line 24, column 5: cannot assign to variable 'const' which is a constant
        const := "NO.1" + float;
        ^
```
但按照 spec 順序 在發現是 constant variable 時不是就應該要跳過 expression 嗎？

**Comment by Naetw** [comment]
Hi, @chengchingwen 

語意檢查的順序是子節點先找，找完才來檢查當前節點的語意：

```
void visitXXXNode(/* emitted for simplicity */) {
    /*
     * 1. Push a new symbol table if this node forms a scope.
     * 2. Insert the symbol into current symbol table if this node is related to
     *    declaration.
     * 3. Travere child nodes of this node.
     * 4. Perform semantic analyses of this node.
     * 5. Pop the symbol table pushed at the 1st step.
     */
}
```

所以旁邊的 expression 相關錯誤才會比 const 出現得早，且沒有被跳過。

**Comment by chengchingwen** [comment]
Hi @Naetw 

這樣的話 Readme 的

- There is no error in the node of the variable reference (lvalue). (no error message needed here)
- The type of the result of the variable reference cannot be an array type.
- The variable reference cannot be a reference to a constant variable.
- The variable reference cannot be a reference to a loop variable when the context is within a loop body.
- There is no error in the node of the expression. (no error message needed here)
- The type of the result of the expression cannot be an array type.
- The type of the variable reference (lvalue) must be the same as the one of the expression after appropriate type coercion.

是不是應該改為：

- There is no error in the node of the expression. (no error message needed here)
- The type of the result of the expression cannot be an array type.
- There is no error in the node of the variable reference (lvalue). (no error message needed here)
- The type of the result of the variable reference cannot be an array type.
- The variable reference cannot be a reference to a constant variable.
- The variable reference cannot be a reference to a loop variable when the context is within a loop body.
- The type of the variable reference (lvalue) must be the same as the one of the expression after appropriate type coercion.

另外，按照同 group 有錯後面要跳過的方式，expression error 之後也不應該跳 const error 吧？

**Comment by Naetw** [comment]
Hi, @chengchingwen 

> 按照同 group 有錯後面要跳過的方式，expression error 之後也不應該跳 const error 吧？

同 group 的錯指的是列在同個 group 的 rules 依序檢查下來有誤才會跳過，expression 內的加法錯誤是在 BinaryOperator 的其中一個 group 發生的，跟這邊想跳過的 variable reference 的 group 不同 group。

不同 group 間的影響時機已經列在 group rules 裡了，以這個為例就是粗體字那行：

- There is no error in the node of the variable reference (lvalue). (no error message needed here)
- The type of the result of the variable reference cannot be an array type.
- The variable reference cannot be a reference to a constant variable.
- The variable reference cannot be a reference to a loop variable when the context is within a loop body.
- **There is no error in the node of the expression. (no error message needed here)**
- The type of the result of the expression cannot be an array type.
- The type of the variable reference (lvalue) must be the same as the one of the expression after appropriate type coercion.

這個順序設計的目的是讓編譯器能夠「盡量」找出能找的錯誤，不能判斷的再跳離（不能判斷的在這邊就是指說 string + float 不知道該以什麼型別作為運算結果）。

不知道這樣有沒有釐清你覺得奇怪的地方？

**Comment by chengchingwen** [comment]
大概理解了
