### ISSUE TITLE
期末考試安排

### ISSUE THREAD

**Issue by rum2mojito** [compiler-s20/discussion#93]
如題，請問期末考試安排在什麼時候，以及考試範圍～謝謝！

**Comment by ypyou** [comment]
@compiler-s20/2020-students 
The exams for both classes will be held in the final exam week; more specifically, June 23 for regular students and June 24 for in-service students. The exam scope covers all the topics discussed after the midterm exam.

**Comment by pohunghuang-nctu** [comment]
能否請問明天考試在哪個教室(6/24)以及考試時間是幾點到幾點? (in-service)

**Comment by YSHsieh7777** [comment]
應該是跟期中考一樣
Exam time: 18:30-20:20
Exam place: EC122

**Comment by pohunghuang-nctu** [comment]
謝謝回覆
