### ISSUE TITLE
VariableNode kind的問題

### ISSUE THREAD

**Issue by XiaoLeS** [compiler-s20/discussion#95]
想請問VariableNode中kind的資訊可能來源。
如果是單純判斷是variable或者constant或許可以用ConstantValueNode是否為null來判斷，但是如果是loop_var或者parameter又是怎麼判斷的呢？

不好意思麻煩了ＱＱ

**Comment by XiaoLeS** [comment]
目前想到另一個方法是透過visitChildNode多個參數來傳遞parentNode的資訊

**Comment by idoleat** [comment]
我的做法是用另外一個 class 來當 manager 管理 (我有可能會把他拆成兩個)，包括記住最近一個被存進 table 的symbol entry，以及目前 travers 的狀態等。

可能不是個乾淨的好做法，但是大部分情況還行的通。詳細 manager 的內容我沒辦法告訴你，因為隨時可能被我改掉，因為我也還沒寫完

**Comment by Naetw** [comment]
Hi, @XiaoLeS 

你可以讓 SemanticAnalyzer 維護一個當前的 context (function, for loop, .etc.)，然後在建構新的 symbol entry 時，就可以利用這個 context 資訊達到你想做的事。

**Comment by XiaoLeS** [comment]
@idoleat @Naetw 感謝兩位, 我繼續思考看看！
