### ISSUE TITLE
VariableReference問題

### ISSUE THREAD

**Issue by XiaoLeS** [compiler-s20/discussion#98]
在助教的範例中是用stack來做symbol tables的, 但是在檢查variable reference的時候需要去看其他scope有沒有declare過這個variable, 這個時候stack沒有辦法讓我去看前面的stack（只能看最上面的）。

雖然改用vector好像就可以了, 但是還是很想知道如果不用vector的話有什麼其他的方法呢？又或者說, 助教當初為什麼會選擇用stack呢？

**Comment by Naetw** [comment]
Hi, @XiaoLeS 

那邊確實是寫錯了，那邊只是想表達我們可以用 LIFO 的特性去簡單地處理 symbol tables，以 single-pass 來說實作上使用 vector 是比較合適的。
